function [elements,chem] = elements_database
%% 0a Create array with elements entries
elements = {'H';'He';...
            'Li';'Be';'B';'C';'N';'O';'F';'Ne';...
            'Na';'Mg';'Al';'Si';'P';'S';'Cl';'Ar';...
            'K';'Ca';'Sc';'Ti';'V';'Cr';'Mn';'Fe';'Co';'Ni';'Cu';'Zn';'Ga';'Ge';'As';'Se';'Br';'Kr';...
            'Rb';'Sr';'Y';'Zr';'Nb';'Mo';'Tc';'Ru';'Rh';'Pd';'Ag';'Cd';'In';'Sn';'Sb';'Te';'I';'Xe';...
            'Cs';'Ba';'La';'Ce';'Pr';'Nd';'Pm';'Sm';'Eu';'Gd';'Tb';'Dy';'Ho';'Er';'Tm';'Yb';'Lu';'Hf';'Ta';'W';'Re';'Os';'Ir';'Pt';'Au';'Hg';'Tl';'Pb';'Bi';'Po';'At';'Rn';...
            'Fr';'Ra';'Ac';'Th';'Pa';'U';'Np';'Pu';'Am';'Cm';'Bk';'Cf';'Es';'Fm';'Md';'No';'Lr';...
            'Rf';'Db';'Sg';'Bh';'Hs';'Mt';'Ds';'Rg';'Cn';'Uut';'Fl';'Uup';'Lv';'Uus';'Uuo'};
%% 0b Create structure for chemical element data
chem = struct;
%% 1 Hydrogen
chem.H  = struct('name','Hydrogen', ...
                 'symbol','H', ...
                 'atomicnumber',1, ...
                 'state','gaseous',...
                 'molarweight',1.00794, ...
                 'electronegativity',1.6 ...
                 );               
%% 2 Helium
chem.He = struct('name','Helium',...
                 'symbol','He', ...
                 'atomicnumber',2, ...
                 'state','gaseous',...
                 'molarweight',4.0026, ...
                 'electronegativity',[] ...
                 );                       
%% 3 Lithium
chem.Li = struct('name','Lithium',...
                  'symbol','Li', ...
                  'atomicnumber',3, ...
                  'state','solid',...
                  'molarweight',6.941, ...
                  'electronegativity',1.0 ...
                  );
%% 4 Beryllium
chem.Be = struct('name','Beryllium',...
                  'symbol','Be', ...
                  'atomicnumber',4, ...
                  'state','solid',...
                  'molarweight',9.012182, ...
                  'electronegativity',1.5 ...
                  );
%% 5 Boron
chem.B  = struct('name','Boron',...
                  'symbol','B', ...
                  'atomicnumber',5, ...
                  'state','solid',...
                  'molarweight',10.811, ...
                  'electronegativity',2.0 ...
                  );
%% 6 Carbon
chem.C  = struct('name','Carbon',...
                  'symbol','C', ...
                  'atomicnumber',6, ...
                  'state','solid',...
                  'molarweight',12.0107, ...
                  'electronegativity',2.5 ...
                  );
%% 7 Nitrogen
chem.N  = struct('name','Nitrogen',...
                 'symbol','N', ...
                 'atomicnumber',7, ...
                 'state','gaseous',...
                 'molarweight',14.0067, ...
                 'electronegativity',3.1 ...
                 );
%% 8 Oxygen
chem.O  = struct('name','Oxygen',...
                 'symbol','O', ...
                 'atomicnumber',8, ...
                 'state','gaseous',...
                 'molarweight',15.9994, ...
                 'electronegativity',3.5 ...
                 );
%% 9 Flourine
chem.F  = struct('name','Flourine',...
                 'symbol','F', ...
                 'atomicnumber',9, ...
                 'state','gaseous',...
                 'molarweight',18.9984, ...
                 'electronegativity',4.1 ...
                 );
%% 10 Neon
chem.Ne = struct('name','Neon',...
                 'symbol','Ne', ...
                 'atomicnumber',10, ...
                 'state','gaseous',...
                 'molarweight',20.1797, ...
                 'electronegativity',[] ...
                 );
%% 11 Sodium
chem.Na = struct('name','Sodium',...
                  'symbol','Na', ...
                  'atomicnumber',11, ...
                  'state','solid',...
                  'molarweight',22.989770, ...
                  'electronegativity',1.0 ...
                  );
%% 12 Magnesium
chem.Mg  = struct('name','Magnesium',...
                  'symbol','Mg', ...
                  'atomicnumber',12, ...
                  'state','solid',...
                  'molarweight',24.3050, ...
                  'electronegativity',1.2 ...
                  );
%% 13 Aluminium
chem.Al  = struct('name','Aluminium',...
                  'symbol','Al', ...
                  'atomicnumber',13, ...
                  'state','solid',...
                  'molarweight',26.9815, ...
                  'electronegativity',1.5 ...
                  );
%% 14 Silicon
chem.Si = struct('name','Silicon',...
                  'symbol','Si', ...
                  'atomicnumber',14, ...
                  'state','solid',...
                  'molarweight',28.0855, ...
                  'electronegativity',1.7 ...
                  );
%% 15 Phosphorus
chem.P  = struct('name','Phosphorus',...
                  'symbol','P', ...
                  'atomicnumber',15, ...
                  'state','solid',...
                  'molarweight',30.9737, ...
                  'electronegativity',2.1 ...
                  );
%% 16 Sulfur
chem.S  = struct('name','Sulfur',...
                  'symbol','S', ...
                  'atomicnumber',16, ...
                  'state','solid',...
                  'molarweight',32.065, ...
                  'electronegativity',2.4 ...
                  );
%% 17 Chlorine
chem.Cl = struct('name','Chlorine',...
                 'symbol','Cl', ...
                 'atomicnumber',17, ...
                 'state','gaseous',...
                 'molarweight',35.453, ...
                 'electronegativity',3.5 ...
                 );
%% 18 Argon
chem.Ar   = struct('name','Argon',...
                   'symbol','Ar', ...
                   'atomicnumber',18, ...
                   'state','gaseous',...
                   'molarweight',39.948, ...
                   'electronegativity',[] ...
                   );
%% 19 Potassium
chem.K   = struct('name','Potassium',...
                  'symbol','K', ...
                  'atomicnumber',19, ...
                  'state','solid',...
                  'molarweight',39.0983, ...
                  'electronegativity',0.9 ...
                  );
%% 20 Calcium
chem.Ca = struct('name','Calcium',...
                  'symbol','Ca', ...
                  'atomicnumber',20, ...
                  'state','solid',...
                  'molarweight',40.078, ...
                  'electronegativity',1.0 ...
                  );
%% 21 Scandium
chem.Sc = struct('name','Scandium',...
                  'symbol','Sc', ...
                  'atomicnumber',21, ...
                  'state','solid',...
                  'molarweight',44.955910, ...
                  'electronegativity',1.2 ...
                  );
%% 22 Titanium
chem.Ti  = struct('name','Titanium',...
                  'symbol','Ti', ...
                  'atomicnumber',22, ...
                  'state','solid',...
                  'molarweight',47.867, ...
                  'electronegativity',1.3 ...
                  );
%% 23 Vanadium
chem.V   = struct('name','Vanadium',...
                  'symbol','V', ...
                  'atomicnumber',23, ...
                  'state','solid',...
                  'molarweight',50.941, ...
                  'electronegativity',1.5 ...
                  );
%% 24 Chromium
chem.Cr  = struct('name','Chromium',...
                  'symbol','Cr', ...
                  'atomicnumber',24, ...
                  'state','solid',...
                  'molarweight',51.996, ...
                  'electronegativity',1.6 ...
                  );
%% 25 Manganese
chem.Mn  = struct('name','Manganese',...
                  'symbol','Mn', ...
                  'atomicnumber',25, ...
                  'state','solid',...
                  'molarweight',54.938, ...
                  'electronegativity',1.6 ...
                  );
%% 26 Fe
chem.Fe  = struct('name','Iron',...
                  'symbol','Fe', ...
                  'atomicnumber',26, ...
                  'state','solid',...
                  'molarweight',55.845, ...
                  'electronegativity',1.6 ...
                  );
%% 27 Cobalt
chem.Co  = struct('name','Cobalt',...
                  'symbol','Co', ...
                  'atomicnumber',27, ...
                  'state','solid',...
                  'molarweight',58.9332, ...
                  'electronegativity',1.7 ...
                  );
%% 28 Nickel
chem.Ni  = struct('name','Nicker',...
                  'symbol','Ni', ...
                  'atomicnumber',28, ...
                  'state','solid',...
                  'molarweight',58.693, ...
                  'electronegativity',1.8 ...
                  );
%% 29 Copper
chem.Cu = struct('name','Copper',...
                  'symbol','Cu', ...
                  'atomicnumber',29, ...
                  'state','solid',...
                  'molarweight',63.546, ...
                  'electronegativity',1.8 ...
                  );
%% 30 Zinc
chem.Zn = struct('name','Zinc',...
                  'symbol','Zi', ...
                  'atomicnumber',30, ...
                  'state','solid',...
                  'molarweight',65.409, ...
                  'electronegativity',1.7 ...
                  );
%% 31 Gallium
chem.Ga = struct('name','Gallium',...
                  'symbol','Ga', ...
                  'atomicnumber',31, ...
                  'state','solid',...
                  'molarweight',69.723, ...
                  'electronegativity',1.8 ...
                  );
%% 32 Germanium
chem.Ge = struct('name','Copper',...
                  'symbol','Ni', ...
                  'atomicnumber',32, ...
                  'state','solid',...
                  'molarweight',72.64, ...
                  'electronegativity',1.8 ...
                  );
%% 33 Arsenic
chem.As = struct('name','Arsenic',...
                  'symbol','As', ...
                  'atomicnumber',33, ...
                  'state','solid',...
                  'molarweight',74.9216, ...
                  'electronegativity',2.2 ...
                  );
%% 34 Selenium
chem.Se = struct('name','Selenium',...
                  'symbol','Se', ...
                  'atomicnumber',34, ...
                  'state','solid',...
                  'molarweight',78.96, ...
                  'electronegativity',2.5 ...
                  );
%% 35 Bromine
chem.Br = struct('name','Bromine',...
                 'symbol','Br', ...
                 'atomicnumber',35, ...
                 'state','liquid',...
                 'molarweight',79.904, ...
                 'electronegativity',2.7 ...
                 );
%% 36 Krypton
chem.Kr = struct('name','Krypton',...
                 'symbol','Kr', ...
                 'atomicnumber',36, ...
                 'state','gaseous',...
                 'molarweight',83.798, ...
                 'electronegativity',[] ...
                 );
%% 37 Rubidium
chem.Rb = struct('name','Rubidium',...
                  'symbol','Rb', ...
                  'atomicnumber',37, ...
                  'state','solid',...
                  'molarweight',85.4678, ...
                  'electronegativity',0.9 ...
                  );
%% 38 Strontium
chem.Sr = struct('name','Strontium',...
                  'symbol','Sr', ...
                  'atomicnumber',38, ...
                  'state','solid',...
                  'molarweight',87.62, ...
                  'electronegativity',1.0 ...
                  );          
%% 39 Yttrium
chem.Y  = struct('name','Yttrium',...
                  'symbol','Y', ...
                  'atomicnumber',39, ...
                  'state','solid',...
                  'molarweight',88.90585, ...
                  'electronegativity',1.1 ...
                  );          
%% 40 Zirconium
chem.Zr = struct('name','Zirconium',...
                  'symbol','Zr', ...
                  'atomicnumber',40, ...
                  'state','solid',...
                  'molarweight',91.224, ...
                  'electronegativity',1.2 ...
                  );      
%% 41 Niobium
chem.Nb = struct('name','Niobium',...
                  'symbol','Nb', ...
                  'atomicnumber',41, ...
                  'state','solid',...
                  'molarweight',92.906, ...
                  'electronegativity',1.2 ...
                  );      
%% 42 Molybdenum
chem.Mo = struct('name','Molybdenum',...
                  'symbol','Mo', ...
                  'atomicnumber',42, ...
                  'state','solid',...
                  'molarweight',95.94, ...
                  'electronegativity',1.3 ...
                  );     
%% 43 Technetium
chem.Tc = struct('name','Technetium',...
                 'symbol','Tc', ...
                 'atomicnumber',43, ...
                 'state','radioactive',...
                 'molarweight','98.9063*', ...
                 'electronegativity',1.4 ...
                 );      
%% 44 Ruthenium
chem.Ru = struct('name','Ruthenium',...
                  'symbol','Ru', ...
                  'atomicnumber',44, ...
                  'state','solid',...
                  'molarweight',101.07, ...
                  'electronegativity',1.4 ...
                  );      
%% 45 Rhodium
chem.Rh = struct('name','Rhodium',...
                  'symbol','Rh', ...
                  'atomicnumber',45, ...
                  'state','solid',...
                  'molarweight',102.905, ...
                  'electronegativity',1.5 ...
                  );      
%% 46 Palladium
chem.Pd = struct('name','Palladium',...
                  'symbol','Pa', ...
                  'atomicnumber',46, ...
                  'state','solid',...
                  'molarweight',106.42, ...
                  'electronegativity',1.2 ...
                  );      
%% 47 Silver
chem.Ag = struct('name','Silver',...
                  'symbol','Ag', ...
                  'atomicnumber',47, ...
                  'state','solid',...
                  'molarweight',107.868, ...
                  'electronegativity',1.4 ...
                  );      
%% 48 Cadmium
chem.Cd = struct('name','Cadmium',...
                  'symbol','Cd', ...
                  'atomicnumber',48, ...
                  'state','solid',...
                  'molarweight',112.411, ...
                  'electronegativity',1.5 ...
                  );      
%% 49 Indium
chem.In = struct('name','Indium',...
                  'symbol','In', ...
                  'atomicnumber',49, ...
                  'state','solid',...
                  'molarweight',114.818, ...
                  'electronegativity',1.5 ...
                  ); 
%% 50 Tin
chem.Sn = struct('name','Tin',...
                  'symbol','Sn', ...
                  'atomicnumber',50, ...
                  'state','solid',...
                  'molarweight',118.710, ...
                  'electronegativity',1.7 ...
                  );      
%% 51 Antimony
chem.Sb = struct('name','Antimony',...
                  'symbol','Sb', ...
                  'atomicnumber',51, ...
                  'state','solid',...
                  'molarweight',121.760, ...
                  'electronegativity',1.8 ...
                  );      
%% 52 Tellurium
chem.Te = struct('name','Tellurium',...
                  'symbol','Te', ...
                  'atomicnumber',52, ...
                  'state','solid',...
                  'molarweight',127.60, ...
                  'electronegativity',2.0 ...
                  );      
%% 53 Iodine
chem.I  = struct('name','Iodine',...
                  'symbol','I', ...
                  'atomicnumber',53, ...
                  'state','solid',...
                  'molarweight',126.904, ...
                  'electronegativity',2.2 ...
                  );
%% 54 Xenon
chem.Xe = struct('name','Xenon',...
                 'symbol','Xe', ...
                 'atomicnumber',54, ...
                 'state','gaseous',...
                 'molarweight',131.293, ...
                 'electronegativity',[] ...
                 );      
%% 55 Caesium
chem.Cs = struct('name','Caesium',...
                  'symbol','Cs', ...
                  'atomicnumber',55, ...
                  'state','solid',...
                  'molarweight',132.90545, ...
                  'electronegativity',1.0 ...
                  ); 
%% 56 Barium
chem.Ba = struct('name','Barium',...
                  'symbol','Ba', ...
                  'atomicnumber',56, ...
                  'state','solid',...
                  'molarweight',137.327, ...
                  'electronegativity',1.0 ...
                  );
%% 57 Lanthanum
chem.La = struct('name','Lanthanum',...
                  'symbol','La', ...
                  'atomicnumber',57, ...
                  'state','solid',...
                  'molarweight',138.906, ...
                  'electronegativity',1.1 ...
                  );
%% 58 Cerium
chem.Ce = struct('name','Cerium',...
                  'symbol','Ce', ...
                  'atomicnumber',58, ...
                  'state','solid',...
                  'molarweight',140.116, ...
                  'electronegativity',1.1 ...
                  );
%% 59 Praseodymium
chem.Pr = struct('name','Praseodymium',...
                  'symbol','Pr', ...
                  'atomicnumber',59, ...
                  'state','solid',...
                  'molarweight',140.908, ...
                  'electronegativity',1.1 ...
                  );
%% 60 Neodymium
chem.Nd = struct('name','Neodymium',...
                  'symbol','Nd', ...
                  'atomicnumber',60, ...
                  'state','solid',...
                  'molarweight',144.24, ...
                  'electronegativity',1.1 ...
                  );
%% 61 Promethium
chem.Pm = struct('name','Promethium',...
                 'symbol','Pm', ...
                 'atomicnumber',61, ...
                 'state','radioactive',...
                 'molarweight','146.915*', ...
                 'electronegativity',1.1 ...
                 );
%% 62 Samarium
chem.Sm = struct('name','Samarium',...
                  'symbol','Sm', ...
                  'atomicnumber',62, ...
                  'state','solid',...
                  'molarweight',150.36, ...
                  'electronegativity',1.1 ...
                  );
%% 63 Europium
chem.Eu = struct('name','Europium',...
                  'symbol','Eu', ...
                  'atomicnumber',63, ...
                  'state','solid',...
                  'molarweight',151.964, ...
                  'electronegativity',1.0 ...
                  );
%% 64 Gadolinium
chem.Gd = struct('name','Gadolimium',...
                  'symbol','Gd', ...
                  'atomicnumber',64, ...
                  'state','solid',...
                  'molarweight',157.25, ...
                  'electronegativity',1.1 ...
                  );
%% 65 Terbium
chem.Tb = struct('name','Terbium',...
                  'symbol','Tb', ...
                  'atomicnumber',65, ...
                  'state','solid',...
                  'molarweight',158.925, ...
                  'electronegativity',1.1 ...
                  );
%% 66 Dysprosium 
chem.Dy = struct('name','Dysprosium',...
                  'symbol','Dy', ...
                  'atomicnumber',66, ...
                  'state','solid',...
                  'molarweight',162.500, ...
                  'electronegativity',1.1 ...
                  );
%% 67 Holmium
chem.Ho = struct('name','Holmium',...
                  'symbol','Ho', ...
                  'atomicnumber',67, ...
                  'state','solid',...
                  'molarweight',164.930, ...
                  'electronegativity',1.1 ...
                  );
%% 68 Erbium
chem.Er = struct('name','Erbium',...
                  'symbol','Er', ...
                  'atomicnumber',68, ...
                  'state','solid',...
                  'molarweight',167.259, ...
                  'electronegativity',1.1 ...
                  );
%% 69 Thulium
chem.Tm = struct('name','Thulium',...
                  'symbol','Tm', ...
                  'atomicnumber',69, ...
                  'state','solid',...
                  'molarweight',168.934, ...
                  'electronegativity',1.1 ...
                  );
%% 70 Ytterbium
chem.Yb = struct('name','Ytterbium',...
                  'symbol','Yb', ...
                  'atomicnumber',70, ...
                  'state','solid',...
                  'molarweight',173.04, ...
                  'electronegativity',1.1 ...
                  );
%% 71 Lutetium
chem.Lu = struct('name','Lutetium',...
                  'symbol','Lu', ...
                  'atomicnumber',71, ...
                  'state','solid',...
                  'molarweight',174.967, ...
                  'electronegativity',1.1 ...
                  );
%% 72 Hafnium
chem.Hf = struct('name','Hafnium',...
                  'symbol','Hf', ...
                  'atomicnumber',72, ...
                  'state','solid',...
                  'molarweight',178.49, ...
                  'electronegativity',1.2 ...
                  );
%% 73 Tantalum
chem.Ta = struct('name','Tantalum',...
                  'symbol','Ta', ...
                  'atomicnumber',73, ...
                  'state','solid',...
                  'molarweight',180.9479, ...
                  'electronegativity',1.0 ...
                  );
%% 74 Tungsten
chem.W  = struct('name','Tungsten',...
                  'symbol','W', ...
                  'atomicnumber',74, ...
                  'state','solid',...
                  'molarweight',183.84, ...
                  'electronegativity',1.4 ...
                  );
%% 75 Rhenium
chem.Re  = struct('name','Rhenium',...
                  'symbol','Re', ...
                  'atomicnumber',75, ...
                  'state','solid',...
                  'molarweight',186.207, ...
                  'electronegativity',1.5 ...
                  );
%% 76 Osmium
chem.Os = struct('name','Osmium',...
                  'symbol','Os', ...
                  'atomicnumber',76, ...
                  'state','solid',...
                  'molarweight',190.23, ...
                  'electronegativity',1.5 ...
                  );
%% 77 Iridium
chem.Ir  = struct('name','Iridium',...
                  'symbol','Ir', ...
                  'atomicnumber',77, ...
                  'state','solid',...
                  'molarweight',192.217, ...
                  'electronegativity',1.6 ...
                  );
%% 78 Platinum
chem.Pt  = struct('name','Platinum',...
                  'symbol','Pt', ...
                  'atomicnumber',78, ...
                  'state','solid',...
                  'molarweight',195.078, ...
                  'electronegativity',1.4 ...
                  );
%% 79 Gold
chem.Au  = struct('name','Gold',...
                  'symbol','Au', ...
                  'atomicnumber',79, ...
                  'state','solid',...
                  'molarweight',196.9665, ...
                  'electronegativity',1.4 ...
                  );
%% 80 Mercury
chem.Hg  = struct('name','Mercury',...
                  'symbol','Hg', ...
                  'atomicnumber',80, ...
                  'state','liquid',...
                  'molarweight',200.59, ...
                  'electronegativity',1.5 ...
                  );
%% 81 Thallium
chem.Tl = struct('name','Thallium',...
                  'symbol','Tl', ...
                  'atomicnumber',81, ...
                  'state','solid',...
                  'molarweight',204.383, ...
                  'electronegativity',1.4 ...
                  );
%% 82 Lead
chem.Pb  = struct('name','Lead',...
                  'symbol','Pb', ...
                  'atomicnumber',82, ...
                  'state','solid',...
                  'molarweight',207.2, ...
                  'electronegativity',1.6 ...
                  );
%% 83 Bismuth
chem.Bi  = struct('name','Bismuth',...
                  'symbol','Bi', ...
                  'atomicnumber',83, ...
                  'state','solid',...
                  'molarweight',208.980, ...
                  'electronegativity',1.7 ...
                  );
%% 84 Polonium
chem.Po  = struct('name','Polonium',...
                  'symbol','Po', ...
                  'atomicnumber',84, ...
                  'state','radioactive',...
                  'molarweight','208.9824*', ...
                  'electronegativity',1.8 ...
                  );
%% 85 Astatine
chem.At  = struct('name','Astatine',...
                  'symbol','At', ...
                  'atomicnumber',85, ...
                  'state','radioactive',...
                  'molarweight','209.9871*', ...
                  'electronegativity',2.0 ...
                  );
%% 86 Radon
chem.Rn  = struct('name','Radon',...
                  'symbol','Rn', ...
                  'atomicnumber',86, ...
                  'state','radioactive',...
                  'molarweight','222.0176*', ...
                  'electronegativity',[] ...
                  );
%% 87 Francium
chem.Fr  = struct('name','Francium',...
                  'symbol','Fr', ...
                  'atomicnumber',87, ...
                  'state','radioactive',...
                  'molarweight','223.0197*', ...
                  'electronegativity',0.9 ...
                  );
%% 88 Radium
chem.Ra  = struct('name','Radium',...
                  'symbol','Ra', ...
                  'atomicnumber',88, ...
                  'state','radioactive',...
                  'molarweight','226.0254*', ...
                  'electronegativity',1.0 ...
                  );
%% 89 Actinium
chem.Ac  = struct('name','Actinium',...
                  'symbol','Ac', ...
                  'atomicnumber',89, ...
                  'state','radioactive',...
                  'molarweight','227.028*', ...
                  'electronegativity',1.0 ...
                  );
%% 90 Thorium
chem.Th  = struct('name','Thorium',...
                  'symbol','Th', ...
                  'atomicnumber',90, ...
                  'state','radioactive',...
                  'molarweight','232.038*', ...
                  'electronegativity',1.1 ...
                  );
%% 91 Protactinium
chem.Pa  = struct('name','Protactinium',...
                  'symbol','Pa', ...
                  'atomicnumber',91, ...
                  'state','radioactive',...
                  'molarweight','231.036*', ...
                  'electronegativity',1.1 ...
                  );
%% 92 Uranium
chem.U   = struct('name','Uranium',...
                  'symbol','U', ...
                  'atomicnumber',92, ...
                  'state','radioactive',...
                  'molarweight','238.029*', ...
                  'electronegativity',1.2 ...
                  );
%% 93 Neptunium
chem.Np  = struct('name','Neptunium',...
                  'symbol','Np', ...
                  'atomicnumber',93, ...
                  'state','radioactive',...
                  'molarweight','237.048*', ...
                  'electronegativity',1.2 ...
                  );
%% 94 Plutonium
chem.Pu  = struct('name','Plutonium',...
                  'symbol','Pu', ...
                  'atomicnumber',94, ...
                  'state','radioactive',...
                  'molarweight','244.064*', ...
                  'electronegativity',1.2 ...
                  );
%% 95 Americium
chem.Am = struct('name','Americium',...
                  'symbol','Am', ...
                  'atomicnumber',95, ...
                  'state','synthetic',...
                  'molarweight','243.061*', ...
                  'electronegativity',[] ...
                  );
%% 96 Curium
chem.Cm  = struct('name','Curium',...
                  'symbol','Cm', ...
                  'atomicnumber',96, ...
                  'state','synthetic',...
                  'molarweight','247.070*', ...
                  'electronegativity',[] ...
                  );
%% 97 Berkelium
chem.Bk  = struct('name','Berkelium',...
                  'symbol','Bk', ...
                  'atomicnumber',97, ...
                  'state','synthetic',...
                  'molarweight','247.0703*', ...
                  'electronegativity',[] ...
                  );
%% 98 Californium
chem.Cf  = struct('name','Californium',...
                  'symbol','Cf', ...
                  'atomicnumber',98, ...
                  'state','synthetic',...
                  'molarweight','251.0796*', ...
                  'electronegativity',[] ...
                  );
%% 99 Einsteinium
chem.Es  = struct('name','Einsteinium',...
                  'symbol','Es', ...
                  'atomicnumber',99, ...
                  'state','synthetic',...
                  'molarweight','252.083*', ...
                  'electronegativity',[] ...
                  );
%% 100 Fermium
chem.Fm = struct('name','Fermium',...
                  'symbol','Fm', ...
                  'atomicnumber',100, ...
                  'state','synthetic',...
                  'molarweight','257.095*', ...
                  'electronegativity',[] ...
                  );
%% 101 Mendelevium
chem.Md = struct('name','Mendelevium',...
                 'symbol','Md', ...
                 'atomicnumber',101, ...
                 'state','synthetic',...
                 'molarweight','258.098*', ...
                 'electronegativity',[] ...
                  );
%% 102 Nobelium
chem.No  = struct('name','Nobelium',...
                  'symbol','No', ...
                  'atomicnumber',102, ...
                  'state','synthetic',...
                  'molarweight','259.101*', ...
                  'electronegativity',[] ...
                  );
%% 103 Lawrencium
chem.Lr  = struct('name','Lawrencium',...
                  'symbol','Lr', ...
                  'atomicnumber',103, ...
                  'state','synthetic',...
                  'molarweight','262.1097*', ...
                  'electronegativity',[] ...
                  );
%% 104 Rutherfordium
chem.Rf  = struct('name','Rutherfordium',...
                  'symbol','Rf', ...
                  'atomicnumber',104, ...
                  'state','synthetic',...
                  'molarweight',[], ...
                  'electronegativity',[] ...
                  );
%% 105 Dubnium
chem.Db  = struct('name','Dubnium',...
                  'symbol','Db', ...
                  'atomicnumber',105, ...
                  'state','synthetic',...
                  'molarweight',[], ...
                  'electronegativity',[] ...
                  );
%% 106 Seaborgium
chem.Sg  = struct('name','Seaborgium',...
                  'symbol','Sg', ...
                  'atomicnumber',106, ...
                  'state','synthetic',...
                  'molarweight',[], ...
                  'electronegativity',[] ...
                  );
%% 107 Bohrium
chem.Bh  = struct('name','Bohrium',...
                  'symbol','Bh', ...
                  'atomicnumber',107, ...
                  'state','synthetic',...
                  'molarweight',[], ...
                  'electronegativity',[] ...
                  );
%% 108 Hassium
chem.Hs  = struct('name','Hassium',...
                  'symbol','Hs', ...
                  'atomicnumber',108, ...
                  'state','synthetic',...
                  'molarweight',[], ...
                  'electronegativity',[] ...
                  );
%% 109 Mt
chem.Mt  = struct('name','Meitnerium',...
                  'symbol','Mt', ...
                  'atomicnumber',109, ...
                  'state','synthetic',...
                  'molarweight',[], ...
                  'electronegativity',[] ...
                  );
%% 110 Darmstadtium
chem.Ds  = struct('name','Darmstadtium',...
                  'symbol','Ds', ...
                  'atomicnumber',110, ...
                  'state','synthetic',...
                  'molarweight',[], ...
                  'electronegativity',[] ...
                  );
%% 111 Roentgenium
chem.Rg  = struct('name','Roentgenium',...
                  'symbol','Rg', ...
                  'atomicnumber',111, ...
                  'state','synthetic',...
                  'molarweight',[], ...
                  'electronegativity',[] ...
                  );
%% 112 Copernicum
chem.Cn  = struct('name','Copernicium',...
                  'symbol','Cn', ...
                  'atomicnumber',112, ...
                  'state','synthetic',...
                  'molarweight',[], ...
                  'electronegativity',[] ...
                  );
%% 113 Ununtrium
chem.Uut  = struct('name','Ununtrium',...
                  'symbol','Uut', ...
                  'atomicnumber',113, ...
                  'state','synthetic',...
                  'molarweight',[], ...
                  'electronegativity',[] ...
                  );
%% 114 Flevorium
chem.Fl  = struct('name','Flevorium',...
                  'symbol','Fl', ...
                  'atomicnumber',114, ...
                  'state','synthetic',...
                  'molarweight',[], ...
                  'electronegativity',[] ...
                  );
%% 115 Ununpentium
chem.Uup  = struct('name','Ununpentium',...
                  'symbol','Uup', ...
                  'atomicnumber',115, ...
                  'state','synthetic',...
                  'molarweight',[], ...
                  'electronegativity',[] ...
                  );
%% 116 Livermorium
chem.Lv  = struct('name','Livermorium',...
                  'symbol','Lv', ...
                  'atomicnumber',116, ...
                  'state','synthetic',...
                  'molarweight',[], ...
                  'electronegativity',[] ...
                  );
%% 117 Ununseptium
chem.Uus  = struct('name','Ununseptium',...
                  'symbol','Uus', ...
                  'atomicnumber',117, ...
                  'state','synthetic',...
                  'molarweight',[], ...
                  'electronegativity',[] ...
                  );
%% 118 Ununoctium
chem.Uuo  = struct('name','Ununoctium',...
                  'symbol','Uuo', ...
                  'atomicnumber',118, ...
                  'state','synthetic',...
                  'molarweight',[], ...
                  'electronegativity',[] ...
                  );
end