function [control] = fastgapp_control

% Title of the program
control.title = 'FastGAPP v2.0';

% Name of the program
control.program = 'FastGAPP';

% Number valid header entries
control.header.m = 83;
% Valid header and fulltext header entries
control.header.valid = {...
                        'SiO2','silica','SiO_2','wt. %';...
                        'TiO2','titania','TiO_2','wt. %';...
                        'Al2O3','alumina','Al_2O_3','wt. %';...
                        'Fe2O3tot','total iron as iron 3 oxide','Fe_2O_3 total','wt. %';...
                        'Fe2O3','iron 3 oxide','Fe_2O_3','wt. %';...
                        'FeOtot','total iron as iron 2 oxide','FeO total','wt. %';...
                        'FeO','iron 2 oxide','FeO','wt. %';...
                        'MnO','manganese oxide','MnO','wt. %';...
                        'MgO','magnesia','MgO','wt. %';...
                        'CaO','calcium oxide','CaO','wt. %';...
                        'Na2O','sodium oxide','Na_2O','wt. %';...
                        'K2O','potassium oxide','K_2O','wt. %';...
                        'P2O5','phosphorus pentoxide','P_2O_5','wt. %';...
                        'SO3','sulphur trioxide','SO_3','wt. %';...
                        'Cl','chlorine','Cl','wt. %';...
                        'F','fluorine','F','wt. %';...
                        'H2O','water / vapor','H_2O','wt. %';...
                        'CO2','carbon dioxide','CO_2','wt. %';...
                        'LOI','loss-on-ignition','LOI','wt. %';...
                        'Total','total (input data)','Total','wt. %';...
                        'TotF','total (volatile-free, all elements)','TotF','wt. %';...
                        'TotC','total (all elements)','TotC','wt. %';...
                        'TotM','total (main elements and volatiles)','TotM','wt. %';...
                        'TotT','total (only trace elements)','TotT','wt. %';...
                        'Ag','silver','Ag','ppm';...
                        'As','arsenic','As','ppm';...
                        'Au','gold','Au','ppm';...
                        'B','boron','B','ppm';...
                        'Ba','barium','Ba','ppm';...
                        'Be','beryllium','Be','ppm';...
                        'Bi','bismuth','Bi','ppm';...
                        'Cd','cadmium','Cd','ppm';...
                        'Co','cobalt','Co','ppm';...
                        'Cr','chromium','Cr','ppm';...
                        'Cs','caesium','Cs','ppm';...
                        'Cu','copper','Cu','ppm';...
                        'Ga','gallium','Ga','ppm';...
                        'Ge','germanium','Ge','ppm';...
                        'Hf','hafnium','Hf','ppm';...
                        'Hg','mercury','Hg','ppm';...
                        'In','indium','In','ppm';...
                        'Li','lithium','Li','ppm';...
                        'Mo','molybdenum','Mo','ppm';...
                        'Nb','niobium','Nb','ppm';...
                        'Ni','nickel','Ni','ppm';...
                        'Pb','lead','Pb','ppm';...
                        'Rb','rubidium','Rb','ppm';...
                        'Re','rhenium','Re','ppm';...
                        'Sb','antimony','Sb','ppm';...
                        'Sc','scandium','Sc','ppm';...
                        'Se','selenium','Se','ppm';...
                        'Sn','tin','Sn','ppm';...
                        'Sr','strontium','Sr','ppm';...
                        'Ta','tantalum','Ta','ppm';...
                        'Te','tellurium','Te','ppm';...
                        'Th','thorium','Th','ppm';...
                        'Tl','thallium','Tl','ppm';...
                        'U','uranium','U','ppm';...
                        'V','vanadium','V','ppm';...
                        'W','tungsten','W','ppm';...
                        'Y','yttrium','Y','ppm';...
                        'Zn','zinc','Zn','ppm';...
                        'Zr','zirconium','Zr','ppm';...
                        'Ru','ruthenium','Ru','ppm';...
                        'Rh','rhodium','Rh','ppm';...
                        'Pd','palladium','Pd','ppm';...
                        'Os','osmium','Os','ppm';...
                        'Ir','iridium','Ir','ppm';...
                        'Pt','platinum','Pt','ppm';...
                        'La','lanthanum','La','ppm';...
                        'Ce','cerium','Ce','ppm';...
                        'Pr','praseodymium','Pr','ppm';...
                        'Nd','neodymium','Nd','ppm';...
                        'Sm','samarium','Sm','ppm';...
                        'Eu','europium','Eu','ppm';...
                        'Gd','gadolinium','Gd','ppm';...
                        'Tb','terbium','Tb','ppm';...
                        'Dy','dysprosium','Dy','ppm';...
                        'Ho','holmium','Ho','ppm';...
                        'Er','erbium','Er','ppm';...
                        'Tm','thulium','Tm','ppm';...
                        'Yb','ytterbium','Yb','ppm';...
                        'Lu','lutetium','Lu','ppm';...
                        };

% Number of plots
control.plots.m = 83;
% List of plot for button names and plot information
control.plots.list = {...
                      'TAS classification diagram (volcanic rocks I)','linear',{'SiO2';'Na2O + K2O'},{'wt.%';'wt.%'},{'[35 80]';'[0 16]'},'Rock classification (all)','net','all','volcanic','all','TAS classification diagram (volcanic rocks I) (after Le Bas et al., 1986)';...
                      'TAS (discrimination line I)','linear',{'SiO2';'Na2O + K2O'},{'wt.%';'wt.%'},{'[35 80]';'[0 16]'},'Rock classification (all)','division line','all','volcanic','all','TAS (discrimination line I) (after MacDonald, 1968)';...
                      'TAS (discrimination line II)','linear',{'SiO2';'Na2O + K2O'},{'wt.%';'wt.%'},{'[35 80]';'[0 16]'},'Rock classification (all)','division line','all','volcanic','all','TAS (discrimination line II) (after Irvine & Baragar, 1971)';...
                      'TAS classification diagram (volcanic rocks II)','linear',{'SiO2';'Na2O + K2O'},{'wt.%';'wt.%'},{'[30 90]';'[0 20]'},'Rock classification (all)','net','all','volcanic','all','TAS classification diagram (volcanic rocks II) (after Middlemost, 1994)';...
                      'TAS classification diagram (plutonic rocks)','linear',{'SiO2';'Na2O + K2O'},{'wt.%';'wt.%'},{'[30 90]';'[0 20]'},'Rock classification (all)','net','all','plutonic','all','TAS classification diagram (plutonic rocks) (after Middlemost, 1994)';...
                      'TAS classification diagram (volcanic pebbles)','linear',{'SiO2';'Na2O + K2O'},{'wt.%';'wt.%'},{'[32 78]';'[0 18]'},'Rock classification (all)','net','all','pebbles','all','TAS classification diagram (volcanic pebbles) (after Cox et al., 1979)';...
                      'SiO2 vs. Zr/TiO2 classification diagram','semilogx',{'Zr / TiO2';'SiO2'},{'ratio';'wt.%'},{'[0.001 10]';'[40 80]'},'Rock classification (all)','net','all','volcanic','all','SiO2 vs. Zr/TiO2 classification diagram (after Winchester & Floyd, 1977)';...
                      'SiO2 vs. Nb/Y classification diagram','semilogx',{'Nb / Y';'SiO2'},{'ratio';'wt.%'},{'[0.01 10]';'[40 80]'},'Rock classification (all)','net','all','volcanic','all','SiO2 vs. Nb/Y classification diagram (after Winchester & Floyd, 1977)';...
                      'Zr/TiO2 vs. Nb/Y classification diagram','loglog',{'Nb / Y';'Zr / TiO2'},{'ratio';'ratio'},{'[0.01 10]';'[0.001 10]'},'Rock classification (all)','net','all','volcanic','all','Zr/TiO2 vs. Nb/Y classification diagram (after Winchester & Floyd, 1977)';...
                      'Na2O vs. K2O classification diagram','linear',{'Na2O';'K2O'},{'wt.%';'wt.%'},{'[0 8]';'[0 8]'},'Rock classification (all)','net','alkaline','igneous','all','Na2O vs. K2O classification diagram (after Middlemost,1975)';...
                      'AFM classification diagram','ternary',{'MgO';'FeOtot';'Na2O + K2O'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'Rock classification (all)','division line','sub-alkaline','igneous','all','AFM classification diagram (after Irvine & Baragar, 1971)';...
                      'Peraluminity Index vs. Alkalinity Saturation Index','linear',{'ASI';'PI'},{'molar ratio';'molar ratio'},{'[0.25 4]';'[0.25 4]'},'Rock classification (all)','division line','all','igneous','all','Peraluminity Index vs. Alkalinity Saturation Index (after Shand, 1927, Shand, 1943)';...
                      'FeOtot/(MgO+FeOtot) discrimination diagram','linear',{'SiO2';'FeOtot / ( MgO + FeOtot )'},{'wt.%';'ratio'},{'[40 80]';'[0 2]'},'Rock classification (all)','division line','all','igneous','all','FeOtot/(MgO+FeOtot) discrimination diagram (after Frost & Frost, 2008)';...
                      'MALI vs. SiO2 discrimination diagram','linear',{'SiO2';'MALI'},{'wt.%';'ratio'},{'[40 80]';'[-8 12]'},'Rock classification (all)','division line','all','igneous','all','MALI vs. SiO2 discrimination diagram (after Frost & Frost, 2008)';...
                      'Alkalinity Saturation Index vs. SiO2','linear',{'SiO2';'ASI'},{'wt.%';'molar ratio'},{'[40 80]';'[0.0 4]'},'Rock classification (all)','division line','all','igneous','all','Alkalinity Saturation Index vs. SiO2 (after Frost & Frost, 2008)';...
                      'Peraluminity Index vs. SiO2','linear',{'SiO2';'PI'},{'wt.%';'molar ratio'},{'[40 80]';'[0.0 4]'},'Rock classification (all)','division line','all','igneous','all','Peraluminity Index vs. SiO2 (after Frost & Frost, 2008)';...
                      'Sr/Y vs. Y classification diagram','linear',{'Sr';'Sr / Y'},{'ppm';'ratio'},{'[0 60]';'[0 500]'},'Rock classification (all)','fields','all','igneous','all','Sr/Y vs. Y classification diagram (after Hansen et al., 2002)';...
                      'P2O5 vs. Zr discrimation diagram','linear',{'Zr';'P2O5'},{'ppm';'wt.%'},{'[0 500]';'[0 1.2]'},'Rock classification (basalts)','division line','sub-alkaline','igneous','all','P2O5 vs. Zr discrimation diagram (after Floyd & Winchester, 1975)';...
                      'TiO2 vs. Zr/P2O5 discrimation diagram','linear',{'Zr / P2O5';'TiO2'},{'ratio';'wt.%'},{'[0 2000]';'[0 4]'},'Rock classification (basalts)','division line','sub-alkaline','igneous','all','TiO2 vs. Zr/P2O5 discrimation diagram (after Floyd & Winchester, 1975)';...
                      'Nb/Y vs. Zr/P2O5 discrimation diagram','linear',{'Zr / P2O5';'Nb / Y'},{'ratio';'ppm'},{'[0 1500]';'[0 3]'},'Rock classification (basalts)','division line','sub-alkaline','igneous','all','Nb/Y vs. Zr/P2O5 discrimation diagram (after Floyd & Winchester, 1975)';...
                      'K2O vs. SiO2 classification diagram','linear',{'SiO2';'K2O'},{'wt.%';'wt.%'},{'[48 78]';'[0 4]'},'Rock classification (subduction-related)','net','all','plutonic','subduction','K2O vs. SiO2 classification diagram (after Peccerillo and Taylor, 1976)';...
                      'Th vs. Co classification diagram','semilogy invx',{'Co';'Th'},{'ppm';'ppm'},{'[0 70]';'[0.01 100]'},'Rock classification (subduction-related)','net','sub-alkaline','igneous','subduction','Th vs. Co classification diagram (after Hastie et al., 2007)';...
                      'FeOtotal / MgO vs. SiO2 classification diagram','linear',{'SiO2';'FeOtot / MgO'},{'wt.%';'ratio'},{'[45 80]';'[0 6]'},'Rock classification (subduction-related)','division line','sub-alkaline','igneous','subduction','FeOtotal / MgO vs. SiO2 classification diagram (after Miyashiro, 1974)';...
                      'FeOtotal vs. FeOtotal / MgO classification diagram','linear',{'FeOtot / MgO';'FeOtot'},{'ratio';'wt.%'},{'[0 6]';'[0 10]'},'Rock classification (subduction-related)','division line','sub-alkaline','igneous','subduction','FeOtotal vs. FeOtotal / MgO classification diagram (after Miyashiro & Shido, 1975)';...
                      'TiO2 vs. FeOtotal / MgO classification diagram','semilogy',{'FeOtot / MgO';'TiO2'},{'ratio';'wt.%'},{'[0 6]';'[0.1 10]'},'Rock classification (subduction-related)','division line','sub-alkaline','igneous','subduction','TiO2 vs. FeOtotal / MgO classification diagram (after Miyashiro & Shido, 1975)';...
                      'V vs. FeOtotal / MgO classification diagram I','semilogy',{'FeOtot / MgO';'V'},{'ratio';'ppm'},{'[0 6]';'[10 1000]'},'Rock classification (subduction-related)','division line','sub-alkaline','igneous','subduction','V vs. FeOtotal / MgO classification diagram I (after Miyashiro & Shido, 1975)';...
                      'V vs. FeOtotal / MgO classification diagram II','semilogy',{'FeOtot / MgO';'V'},{'ratio';'ppm'},{'[0 7]';'[1 1000]'},'Rock classification (subduction-related)','division line','sub-alkaline','igneous','subduction','V vs. FeOtotal / MgO classification diagram II (after Miyashiro & Shido, 1975)';...
                      'Cr vs. SiO2 classification diagram','semilogy',{'SiO2';'Cr'},{'wt.%';'ppm'},{'[45 65]';'[1 10000]'},'Rock classification (subduction-related)','division line','sub-alkaline','igneous','subduction','Cr vs. SiO2 classification diagram (after Miyashiro & Shido, 1975)';...
                      'V vs. Cr classification diagram','loglog',{'Cr';'V'},{'ratio';'ppm'},{'[1 1000]';'[10 1000]'},'Rock classification (subduction-related)','division line','sub-alkaline','igneous','subduction','V vs. Cr classification diagram (after Miyashiro & Shido, 1975)';...
                      'CaO/(Na2O+K20) vs. SiO2 discrimination diagram','semilogy',{'SiO2';'CaO / ( Na2O + K2O )'},{'wt.%';'ratio'},{'[45 80}';'[0.1 10]'},'Rock classification (subduction-related)','field','andesitic','igneous','subduction','CaO/(Na2O+K20) vs. SiO2 discrimination diagram (after Brown, 1982)';...
                      'Na2O + K2O vs. 10000*Ga/Al granite subdivision','semilogx',{'10000 * Ga / Al';'Na2O + K2O'},{'ratio';'wt.%'},{'[1 10]';'[0 12]'},'Rock classification (granitic)','division line','granitic','igneous','all','Na2O + K2O vs. 10000*Ga/Al granite subdivision (after Whalen et al., 1987)';...
                      '(Na2O + K2O) / CaO vs. 10000*Ga/Al granite subdivision','loglog',{'10000 * Ga / Al';'( Na2O + K2O ) / CaO'},{'ratio';'ratio'},{'[1 10]';'[1 100]'},'Rock classification (granitic)','division line','granitic','igneous','all','(Na2O + K2O) / CaO vs. 10000*Ga/Al granite subdivision (after Whalen et al., 1987)';...
                      'K2O / MgO vs. 10000*Ga/Al granite subdivision','loglog',{'10000 * Ga / Al';'K2O / MgO'},{'ratio';'ratio'},{'[1 10]';'[1 100]'},'Rock classification (granitic)','division line','granitic','igneous','all','K2O / MgO vs. 10000*Ga/Al granite subdivision (after Whalen et al., 1987)';...
                      'FeOtotal / MgO vs. 10000*Ga/Al granite subdivision','loglog',{'10000 * Ga / Al';'FeOtot / MgO'},{'ratio';'ratio'},{'[1 10]';'[1 100]'},'Rock classification (granitic)','division line','granitic','igneous','all','FeOtotal / MgO vs. 10000*Ga/Al granite subdivision (after Whalen et al., 1987)';...
                      'Zr vs. 10000*Ga/Al granite subdivision','loglog',{'10000 * Ga / Al';'Zr'},{'ratio';'ppm'},{'[1 10]';'[10 10000]'},'Rock classification (granitic)','division line','granitic','igneous','all','Zr vs. 10000*Ga/Al granite subdivision (after Whalen et al., 1987)';...
                      'Nb vs. 10000*Ga/Al granite subdivision','loglog',{'10000 * Ga / Al';'Nb'},{'ratio';'ppm'},{'[1 10]';'[1 1000]'},'Rock classification (granitic)','division line','granitic','igneous','all','Nb vs. 10000*Ga/Al granite subdivision (after Whalen et al., 1987)';...
                      'Ce vs. 10000*Ga/Al granite subdivision','loglog',{'10000 * Ga / Al';'Ce'},{'ratio';'ppm'},{'[1 10]';'[10 1000]'},'Rock classification (granitic)','division line','granitic','igneous','all','Ce vs. 10000*Ga/Al granite subdivision (after Whalen et al., 1987)';...
                      'Y vs. 10000*Ga/Al granite subdivision','loglog',{'10000 * Ga / Al';'Y'},{'ratio';'ppm'},{'[1 10]';'[10 1000]'},'Rock classification (granitic)','division line','granitic','igneous','all','Y vs. 10000*Ga/Al granite subdivision (after Whalen et al., 1987)';...
                      'Zn vs. 10000*Ga/Al granite subdivision','loglog',{'10000 * Ga / Al';'Zn'},{'ratio';'ppm'},{'[1 10]';'[10 1000]'},'Rock classification (granitic)','division line','granitic','igneous','all','Zn vs. 10000*Ga/Al granite subdivision (after Whalen et al., 1987)';...
                      'AI vs. 10000*Ga/Al granite subdivision','semilogx',{'10000 * Ga / Al';'AI'},{'ratio';'molar ratio'},{'[1 10]';'[0.5 1.3]'},'Rock classification (granitic)','division line','granitic','igneous','all','AI vs. 10000*Ga/Al granite subdivision (after Whalen et al., 1987)';...
                      'FeOtot / MgO vs. Zr+Nb+Ce+Y granite subdivision','loglog',{'Zr + Nb + Ce + Y';'FeOtot / MgO'},{'ppm';'ratio'},{'[10 10000]';'[1 1000]'},'Rock classification (granitic)','division line','granitic','igneous','all','FeOtot / MgO vs. Zr+Nb+Ce+Y granite subdivision (after Whalen et al., 1987)';...
                      '(Na2O + K2O) / CaO vs. Zr+Nb+Ce+Y granite subdivision','loglog',{'Zr + Nb + Ce + Y';'( Na2O + K2O ) / CaO'},{'ppm';'ratio'},{'[10 10000]';'[1 1000]'},'Rock classification (granitic)','division line','granitic','igneous','all','(Na2O + K2O) / CaO vs. Zr+Nb+Ce+Y granite subdivision (after Whalen et al., 1987)';...
                      'Rb/Nb vs. Y/Nb granite subdivision','loglog',{'Y / Nb';'Rb / Nb'},{'ratio';'ratio'},{'[0.1 10]';'[1 100]'},'Rock classification (granitic)','division line','granitic','igneous','all','Rb/Nb vs. Y/Nb granite subdivision (after Eby, 1992)';...
                      'Y/Nb vs. Sc/Nb granite subdivision','loglog',{'Y / Nb';'Sc / Nb'},{'ratio';'ratio'},{'[0.1 10]';'[0.0001 1]'},'Rock classification (granitic)','division line','granitic','igneous','all','Y/Nb vs. Sc/Nb granite subdivision (after Eby, 1992)';...
                      'Nb-Y-Ga A-type granite subdivision ','ternary',{'3 * Ga';'Nb';'Y'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'Rock classification (granitic)','division line','granitic','igneous','all','Nb-Y-Ga A-type granite subdivision  (after Eby, 1992)';...
                      'Nb-Y-Ce A-type granite subdivision ','ternary',{'Ce';'Nb';'Y'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'Rock classification (granitic)','division line','granitic','igneous','all','Nb-Y-Ce A-type granite subdivision  (after Eby, 1992)';...
                      'Ga/Al vs. Eu/Eu* granite subdivision','linear',{'Eu / Eu*';'10000 * Ga / Al'},{'ratio';'ratio'},{'[0 1]';'[0 8]'},'Rock classification (granitic)','division line','granitic','igneous','all','Ga/Al vs. Eu/Eu* granite subdivision (after Eby, 1992)';...
                      'Yb vs. Al2O3 granite subdivision','semilogy',{'Al2O3';'Yb'},{'wt.%';'ppm'},{'[10 20]';'[0.01 100]'},'Rock classification (granitic)','division line','granitic','igneous','all','Yb vs. Al2O3 granite subdivision (after Arth, 1979)';...
                      'Carbonatite classification diagram I','ternary',{'FeOtot + MnO';'CaO';'MgO'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'Rock classification (carbonatites)','net','carbonatite','igneous','all','Carbonatite classification diagram I (after LeBas & Streckeisen, 1989)';...
                      'Carbonatite classification diagram II','ternary',{'FeOtot + MnO';'CaO';'MgO'},{'molar fraction';'molar fraction';'molar fraction'},{'-';'-';'-'},'Rock classification (carbonatites)','net','carbonatite','igneous','all','Carbonatite classification diagram II (after Gittins & Harmer, 1997)';...
                      'Th/Ta vs. Yb discrimination diagram','linear',{'Yb';'Th / Ta'},{'ppm';'ratio'},{'[0 14]';'[0 25]'},'Geotectonic setting (all)','division lines','basaltic','igneous','all','Th/Ta vs. Yb discrimination diagram (after Gorton & Schandl, 2000)';...
                      'Th/Yb vs. Ta/Yb discrimination diagram I','loglog',{'Ta / Yb';'Th / Yb'},{'ratio';'ratio'},{'[0.01 100]';'[0.01 100]'},'Geotectonic setting (all)','division lines','basaltic','igneous','all','Th/Yb vs. Ta/Yb discrimination diagram I (after Gorton & Schandl, 2000)';...
                      'MnO-TiO2-P2O5 classification diagram','ternary',{'10 * P2O5';'TiO2';'10 * MnO'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'Geotectonic setting (basalts)','net','basaltic','igneous','all','MnO-TiO2-P2O5 classification diagram (after Mullen, 1983)';...
                      'TiO2-K2O-P2O5 classification diagram','ternary',{'P2O5';'TiO2';'K2O'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'Geotectonic setting (basalts)','division line','basaltic','igneous','all','TiO2-K2O-P2O5 classification diagram (after Pearce et al., 1975)';...
                      'Al2O3-FeO-MgO classification diagram','ternary',{'Al2O3';'FeO';'MgO'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'Geotectonic setting (basalts)','net','basaltic','igneous','all','Al2O3-FeO-MgO classification diagram (after Pearce et al., 1977)';...
                      'Zr/Nb vs. Nb/Th geotectonic discrimination diagram','semilogy',{'Nb / Th';'Zr / Nb'},{'ratio';'ratio'},{'[0 30]';'[2 100]'},'Geotectonic setting (basalts)','fields','basaltic','igneous','all','Zr/Nb vs. Nb/Th geotectonic discrimination diagram (after Condie, 2005)';...
                      'Nb/Y vs. Zr/Y geotectonic discrimination diagram','loglog',{'Zr / Y';'Nb / Y'},{'ratio';'ratio'},{'[1 20]';'[0.01 10]'},'Geotectonic setting (basalts)','fields','basaltic','igneous','all','Nb/Y vs. Zr/Y geotectonic discrimination diagram (after Condie, 2005)';...
                      'Nb/Y vs. Zr/Y source discrimination diagram','loglog',{'Zr / Y';'Nb / Y'},{'ratio';'ratio'},{'[1 20]';'[0.01 10]'},'Geotectonic setting (basalts)','division line','basaltic','igneous','all','Nb/Y vs. Zr/Y source discrimination diagram (after Fitton et al., 1997)';...
                      'Zr/4-2Nb-Y geotectonic classification diagram','ternary',{'Y';'2 * Nb';'Zr / 4'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'Geotectonic setting (basalts)','net','basaltic','igneous','all','Zr/4-2Nb-Y geotectonic classification diagram (after Meschede, 1986)';...
                      'Ti vs Zr geotectonic classification diagram','linear',{'Zr';'Ti'},{'ppm';'ppm'},{'[0  200]';'[0 15000]'},'Geotectonic setting (basalts)','net','basaltic','igneous','all','Ti vs Zr geotectonic classification diagram (after Pearce & Cann, 1973)';...
                      'Sr/2-Ti/100-Zr geotectonic discrimination diagram','ternary',{'Sr / 2';'Ti / 100';'Zr'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'Geotectonic setting (basalts)','net','basaltic','igneous','all','Sr/2-Ti/100-Zr geotectonic discrimination diagram (after Pearce & Cann, 1973)';...
                      'Ti/100-3Y-Zr geotectonic discrimination diagram','ternary',{'3 * Y';'Ti / 100';'Zr'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'Geotectonic setting (basalts)','net','basaltic','igneous','all','Ti/100-3Y-Zr geotectonic discrimination diagram (after Pearce & Cann, 1973)';...
                      'Ta-Th-Hf/3 geotectonic discrimination diagram','ternary',{'Ta';'Hf / 3';'Th'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'Geotectonic setting (basalts)','net','basaltic','igneous','all','Ta-Th-Hf/3 geotectonic discrimination diagram (after Wood, 1980)';...
                      'Nb/8-La/10-Y/15 geotectonic classification diagram','ternary',{'Nb / 8';'Y / 15';'La / 10'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'Geotectonic setting (basalts)','net','basaltic','igneous','all','Nb/8-La/10-Y/15 geotectonic classification diagram (after Cabanis & Lecolle, 1989)';...
                      'Nb/La vs. La/Yb geotectonic classification diagram','loglog',{'La / Yb';'Nb / La'},{'ratio';'ratio'},{'[0.4 80]';'[0.09 3]'},'Geotectonic setting (basalts)','net','basaltic','igneous','all','Nb/La vs. La/Yb geotectonic classification diagram (after Hollocher et al., 2012)';...
                      '17.9*Ta/La vs. La/Yb geotectonic classification diagram','loglog',{'La / Yb';'( 17.9 * Ta ) / La'},{'ratio';'ratio'},{'[0.4 80]';'[0.09 3]'},'Geotectonic setting (basalts)','net','basaltic','igneous','all','17.9*Ta/La vs. La/Yb geotectonic classification diagram (after Hollocher et al., 2012)';...
                      '((Nb+17.9*Ta)/2)/La vs. La/Yb geotectonic classification diagram','loglog',{'La / Yb';'( ( Nb + 17.9 * Ta )  / 2 ) / La'},{'ratio';'ratio'},{'[0.4 80]';'[0.09 3]'},'Geotectonic setting (basalts)','net','basaltic','igneous','all','((Nb+17.9*Ta)/2)/La vs. La/Yb geotectonic classification diagram (after Hollocher et al., 2012)';...
                      'Th/La vs. La/Yb geotectonic classification diagram','loglog',{'La / Yb';'Th / La'},{'ratio';'ratio'},{'[0.4 80]';'[0.02 5]'},'Geotectonic setting (basalts)','net','basaltic','igneous','all','Th/La vs. La/Yb geotectonic classification diagram (after Hollocher et al., 2012)';...
                      'V vs. Ti discrimination diagram','linear',{'Ti';'V'},{'ppm';'ratio'},{'[0 30000]';'[0 700]'},'Geotectonic setting (basalts)','division lines','basaltic','igneous','all','V vs. Ti discrimination diagram (after Shervais, 1982)';...
                      'Cr vs. Ti discrimination diagram','loglog',{'Ti';'Cr'},{'ppm';'ppm'},{'[1000 100000]';'[10 10000]'},'Geotectonic setting (basalts)','division lines','basaltic','igneous','all','Cr vs. Ti discrimination diagram (after Pearce, 1975)';...
                      'Cr vs. Y discrimination diagram','loglog',{'Y';'Cr'},{'ppm';'ratio'},{'[1 100]';'[1 10000]'},'Geotectonic setting (basalts)','fields','basaltic','igneous','all','Cr vs. Y discrimination diagram (after Dilek et al., 2007)';...
                      'Zr vs. Ti discrimination diagram','linear',{'Ti';'Zr'},{'ppm';'ratio'},{'[0 10000]';'[0 150]'},'Geotectonic setting (basalts)','fields','basaltic','igneous','all','Zr vs. Ti discrimination diagram (after Dilek & Furnes, 2009)';...
                      'Zr/Y vs. Zr discrimination diagram I','loglog',{'Zr';'Zr / Y'},{'ratio';'ratio'},{'[1 1000]';'[0.1 20]'},'Geotectonic setting (basalts)','fields','basaltic','igneous','all','Zr/Y vs. Zr discrimination diagram I (after Pearce & Norry, 1979)';...
                      'Ti vs. Zr discrimination diagram I','loglog',{'Zr';'Ti'},{'ppm';'ppm'},{'[10 1000]';'[1000 40000]'},'Geotectonic setting (basalts)','fields','basaltic','igneous','all','Ti vs. Zr discrimination diagram I (after Pearce, 1981)';...
                      'K2O/Yb vs. Ta/Yb discrimination diagram','loglog',{'Ta / Yb';'K2O / Yb'},{'ratio';'ratio'},{'[0.01 100]';'[0.01 10]'},'Geotectonic setting (basalts)','fields','basaltic','igneous','all','K2O/Yb vs. Ta/Yb discrimination diagram (after Pearce, 1982)';...
                      'Th/Yb vs. Ta/Yb discrimination diagram II','loglog',{'Ta / Yb';'Th / Yb'},{'ratio';'ratio'},{'[0.01 100]';'[0.01 100]'},'Geotectonic setting (basalts)','fields','basaltic','igneous','all','Th/Yb vs. Ta/Yb discrimination diagram II (after Pearce, 1982)';...
                      'Ti/Y vs. Nb/Y discrimination diagram','loglog',{'Nb / Y';'Ti / Y'},{'ratio';'ratio'},{'[0.01 100]';'[100 2000]'},'Geotectonic setting (basalts)','fields','basaltic','igneous','all','Ti/Y vs. Nb/Y discrimination diagram (after Pearce, 1982)';...
                      'Th/Yb vs. Ta/Yb discrimination diagram III','loglog',{'Ta / Yb';'Th / Yb'},{'ratio';'ratio'},{'[0.01 10]';'[0.01 10]'},'Geotectonic setting (basalts)','fields','basaltic','igneous','all','Th/Yb vs. Ta/Yb discrimination diagram III (after Pearce, 1983)';...
                      'Zr/Y vs. Zr discrimination diagram II','loglog',{'Zr';'Zr / Y'},{'ratio';'ratio'},{'[10 1000]';'[1 10]'},'Geotectonic setting (basalts)','division line','basaltic','igneous','all','Zr/Y vs. Zr discrimination diagram II (after Pearce, 1983)';...
                      'Rb vs. Y + Nb discrimination diagram','loglog',{'Y + Nb';'Rb'},{'ppm';'ppm'},{'[2 2000]';'[1 2000]'},'Geotectonic setting (granitic)','net','granitic','igneous','all','Rb vs. Y + Nb discrimination diagram (after Pearce et al., 1984)';...
                      'Rb vs. Yb + Ta discrimination diagram','loglog',{'Yb + Ta';'Rb'},{'ppm';'ppm'},{'[0.5 200]';'[1 2000]'},'Geotectonic setting (granitic)','net','granitic','igneous','all','Rb vs. Yb + Ta discrimination diagram (after Pearce et al., 1984)';...
                      'Nb vs. Y discrimination diagram','loglog',{'Y';'Nb'},{'ppm';'ppm'},{'[1 2000]';'[1 2000]'},'Geotectonic setting (granitic)','net','granitic','igneous','all','Nb vs. Y discrimination diagram (after Pearce et al., 1984)';...
                      'Yb vs. Ta discrimination diagram','loglog',{'Yb';'Ta'},{'ppm';'ppm'},{'[0.1 100]';'[0.05 100]'},'Geotectonic setting (granitic)','net','granitic','igneous','all','Yb vs. Ta discrimination diagram (after Pearce et al., 1984)';...
                      };
% List of plot for button names and plot information
control.plots.description = {...
                      'Le Bas et al., 1986','Le Bas, M. J. , Le Maitre, R. W. , Streckeisen, A., Zanettin, B., IUGS Subcommission on the Systematics of Igneous Rocks, 1986. A chemical classification of volcanic rocks based on the total alkali–silica diagram. Journal of Petrology 27, 745–750.';...
                      'MacDonald, 1968','MacDonald, G. A., 1968. Composition and origin of Hawaiian lavas. Geological Society of America Memoirs 116, 477-522.';...
                      'Irvine & Baragar, 1971','Irvine, T.N., Baragar, W.R.A., 1971. A Guide to the Chemical Classification of the Common Volcanic Rocks. Canadian Journal of Earth Sciences 8, 523-548.';...
                      'Middlemost, 1994','Middlemost, E.A.K., 1994. Naming materials in the magma/igneous rock system Earth-Science Reviews 37, 215-224.';...
                      'Middlemost, 1994','Middlemost, E.A.K., 1994. Naming materials in the magma/igneous rock system Earth-Science Reviews 37, 215-224.';...
                      'Cox et al., 1979','Cox, K.G., Bell, J.D., Pankhurst R.J., 1979. The interpretation of igneous rocks. George Allen and Unwin, London, 1–450, Chapter 3.';...
                      'Winchester & Floyd, 1977','Winchester, J.A., Floyd, P.A., 1977. Geochemical discrimination of different magma series and their differentiation products using immobile elements. Chemical Geology 21, 291-306.';...
                      'Winchester & Floyd, 1977','Winchester, J.A., Floyd, P.A., 1977. Geochemical discrimination of different magma series and their differentiation products using immobile elements. Chemical Geology 21, 291-306.';...
                      'Winchester & Floyd, 1977','Winchester, J.A., Floyd, P.A., 1977. Geochemical discrimination of different magma series and their differentiation products using immobile elements. Chemical Geology 21, 291-306.';...
                      'Middlemost,1975','Middlemost, E.A.K., 1975. The basalt clan. Earth-Science Reviews 11, 337-364.';...
                      'Irvine & Baragar, 1971','Irvine, T.N., Baragar, W.R.A., 1971. A Guide to the Chemical Classification of the Common Volcanic Rocks. Canadian Journal of Earth Sciences 8, 523-548.';...
                      'Shand, 1927, Shand, 1943','Shand, S.J., 1927. On the relations between silica, alumina, and the bases in eruptive rocks, considered as a means of classification. Geological Magazine, 64, 446-449. Shand, S.J., 1943. Eruptive rocks: Their genesis, composition, and classification, and their relation to ore deposits with a chapter on meteorites. John Wiley & Sons, New York.';...
                      'Frost & Frost, 2008','Frost, B.R., Frost, C.D., 2008. A geochemical classification for feldspathic igneous rocks.  Journal of Petrology, v. 49, p. 1955-1969.';...
                      'Frost & Frost, 2008','Frost, B.R., Frost, C.D., 2008. A geochemical classification for feldspathic igneous rocks.  Journal of Petrology, v. 49, p. 1955-1969.';...
                      'Frost & Frost, 2008','Frost, B.R., Frost, C.D., 2008. A geochemical classification for feldspathic igneous rocks.  Journal of Petrology, v. 49, p. 1955-1969.';...
                      'Frost & Frost, 2008','Frost, B.R., Frost, C.D., 2008. A geochemical classification for feldspathic igneous rocks.  Journal of Petrology, v. 49, p. 1955-1969.';...
                      'Hansen et al., 2002','Hansen, J., Skjerlie, K.P., Pedersen, R.B., and De La Rosa, J., 2002. Crustal melting in the lower parts of island arcs: an example from the Bremanger Granitoid Complex, west Norwegian Caledonides; Contributions to Mineralogy and Petrology, v. 143, p. 316-335.';...
                      'Floyd & Winchester, 1975','Floyd, P.A. and Winchester, J.A., 1975, Magma type and tectonic setting discrimination using immobile elements: Earth and Planetary Science Letters, v. 27, p. 211-218.';...
                      'Floyd & Winchester, 1975','Floyd, P.A. and Winchester, J.A., 1975, Magma type and tectonic setting discrimination using immobile elements: Earth and Planetary Science Letters, v. 27, p. 211-218.';...
                      'Floyd & Winchester, 1975','Floyd, P.A. and Winchester, J.A., 1975, Magma type and tectonic setting discrimination using immobile elements: Earth and Planetary Science Letters, v. 27, p. 211-218.';...
                      'Peccerillo and Taylor, 1976','Peccerillo, A., Taylor, S.R., 1976. Geochemistry of eocene calc-alkaline volcanic rocks from the Kastamonu area, Northern Turkey. Contributions to Mineralogy and Petrology 58, 63-81.';...
                      'Hastie et al., 2007','Hastie, A.R., Kerr, A.C., Pearce, J.A., Mitchell, S.F., 2007. Classification of altered volcanic island arc rocks using immobiletrace elements: development of the Th-Co discrimination diagram. Journal of Petrology 48, 2341-2357.';...
                      'Miyashiro, 1974','Miyashiro, A., 1974, Volcanic rock series in island arcs and active continental margins.  American Journal of Science, v. 274, p. 321-355.';...
                      'Miyashiro & Shido, 1975','Miyashiro, A., and Shido, F., 1975, Tholeiitic and calc-alkaline series in relation to the behaviors of titanium, vanadium, chromium, and nickel.  American Journal of Science, v. 275, p. 265-277.';...
                      'Miyashiro & Shido, 1975','Miyashiro, A., and Shido, F., 1975, Tholeiitic and calc-alkaline series in relation to the behaviors of titanium, vanadium, chromium, and nickel.  American Journal of Science, v. 275, p. 265-277.';...
                      'Miyashiro & Shido, 1975','Miyashiro, A., and Shido, F., 1975, Tholeiitic and calc-alkaline series in relation to the behaviors of titanium, vanadium, chromium, and nickel.  American Journal of Science, v. 275, p. 265-277.';...
                      'Miyashiro & Shido, 1975','Miyashiro, A., and Shido, F., 1975, Tholeiitic and calc-alkaline series in relation to the behaviors of titanium, vanadium, chromium, and nickel.  American Journal of Science, v. 275, p. 265-277.';...
                      'Miyashiro & Shido, 1975','Miyashiro, A., and Shido, F., 1975, Tholeiitic and calc-alkaline series in relation to the behaviors of titanium, vanadium, chromium, and nickel.  American Journal of Science, v. 275, p. 265-277.';...
                      'Miyashiro & Shido, 1975','Miyashiro, A., and Shido, F., 1975, Tholeiitic and calc-alkaline series in relation to the behaviors of titanium, vanadium, chromium, and nickel.  American Journal of Science, v. 275, p. 265-277.';...
                      'Brown, 1982','Brown, G.C., 1982, Calc-alkaline intrusive rocks: their diversity, evolution, and relation to volcanic arcs, p. 437-461. In: Thorp, R.S. (Eds), Andesites: Orogenic Andesites and Related Rocks, John Wiley and Sons, New York, 724 p.';...
                      'Whalen et al., 1987','Whalen, J.B., Currie, K.L., and Chappell, B.W., 1987. S-type granites: geochemical characteristics, discrimination and petrogenesis.  Contributions to Mineralogy and Petrology, v. 95, p. 407-419.';...
                      'Whalen et al., 1987','Whalen, J.B., Currie, K.L., and Chappell, B.W., 1987. S-type granites: geochemical characteristics, discrimination and petrogenesis.  Contributions to Mineralogy and Petrology, v. 95, p. 407-419.';...
                      'Whalen et al., 1987','Whalen, J.B., Currie, K.L., and Chappell, B.W., 1987. S-type granites: geochemical characteristics, discrimination and petrogenesis.  Contributions to Mineralogy and Petrology, v. 95, p. 407-419.';...
                      'Whalen et al., 1987','Whalen, J.B., Currie, K.L., and Chappell, B.W., 1987. S-type granites: geochemical characteristics, discrimination and petrogenesis.  Contributions to Mineralogy and Petrology, v. 95, p. 407-419.';...
                      'Whalen et al., 1987','Whalen, J.B., Currie, K.L., and Chappell, B.W., 1987. S-type granites: geochemical characteristics, discrimination and petrogenesis.  Contributions to Mineralogy and Petrology, v. 95, p. 407-419.';...
                      'Whalen et al., 1987','Whalen, J.B., Currie, K.L., and Chappell, B.W., 1987. S-type granites: geochemical characteristics, discrimination and petrogenesis.  Contributions to Mineralogy and Petrology, v. 95, p. 407-419.';...
                      'Whalen et al., 1987','Whalen, J.B., Currie, K.L., and Chappell, B.W., 1987. S-type granites: geochemical characteristics, discrimination and petrogenesis.  Contributions to Mineralogy and Petrology, v. 95, p. 407-419.';...
                      'Whalen et al., 1987','Whalen, J.B., Currie, K.L., and Chappell, B.W., 1987. S-type granites: geochemical characteristics, discrimination and petrogenesis.  Contributions to Mineralogy and Petrology, v. 95, p. 407-419.';...
                      'Whalen et al., 1987','Whalen, J.B., Currie, K.L., and Chappell, B.W., 1987. S-type granites: geochemical characteristics, discrimination and petrogenesis.  Contributions to Mineralogy and Petrology, v. 95, p. 407-419.';...
                      'Whalen et al., 1987','Whalen, J.B., Currie, K.L., and Chappell, B.W., 1987. S-type granites: geochemical characteristics, discrimination and petrogenesis.  Contributions to Mineralogy and Petrology, v. 95, p. 407-419.';...
                      'Whalen et al., 1987','Whalen, J.B., Currie, K.L., and Chappell, B.W., 1987. S-type granites: geochemical characteristics, discrimination and petrogenesis.  Contributions to Mineralogy and Petrology, v. 95, p. 407-419.';...
                      'Whalen et al., 1987','Whalen, J.B., Currie, K.L., and Chappell, B.W., 1987. S-type granites: geochemical characteristics, discrimination and petrogenesis.  Contributions to Mineralogy and Petrology, v. 95, p. 407-419.';...
                      'Eby, 1992','Eby, G.N., 1992. Chemical subdivision of the A-type granitoids: petrogenetic and tectonic implications. Geology 20(7), 641-644.';...
                      'Eby, 1992','Eby, G.N., 1992. Chemical subdivision of the A-type granitoids: petrogenetic and tectonic implications. Geology 20(7), 641-644.';...
                      'Eby, 1992','Eby, G.N., 1992. Chemical subdivision of the A-type granitoids: petrogenetic and tectonic implications. Geology 20(7), 641-644.';...
                      'Eby, 1992','Eby, G.N., 1992. Chemical subdivision of the A-type granitoids: petrogenetic and tectonic implications. Geology 20(7), 641-644.';...
                      'Eby, 1992','Eby, G.N., 1992. Chemical subdivision of the A-type granitoids: petrogenetic and tectonic implications. Geology 20(7), 641-644.';...
                      'Arth, 1979','Arth, J.G., 1979. Some trace elements in trondhjemites-their implications to magma enesis and paleotectonic setting, p. 123-132. In: Barker, F., ed., Trondhjemites, Dacites and Related Rocks, Elsevier, Amsterdam.';...
                      'LeBas & Streckeisen, 1989','Le Bas, M. J. , Streckeisen, A., and IUGS Subcommission on the Systematics of Igneous Rocks, 1991. The IUGS systematics of igneous rocks. Journal of the Geological Society, 148, 825-833.';...
                      'Gittins & Harmer, 1997','Gittins, J. and Harmer, R.E., 1997, What is ferrocarbonatite? A revised classification. Journal of African Earth Sciences, 25(1), 159-168.';...
                      'Gorton & Schandl, 2000','Gorton, M.P. and Schandl, E.S., 2000, From continents to island arcs: a geochemical index of tectonic setting for arc-related and within-plate felsic to intermediate volcanic rocks.  Canadian Mineralogist, v. 38, p. 1065-1073.';...
                      'Gorton & Schandl, 2000','Gorton, M.P. and Schandl, E.S., 2000, From continents to island arcs: a geochemical index of tectonic setting for arc-related and within-plate felsic to intermediate volcanic rocks.  Canadian Mineralogist, v. 38, p. 1065-1073.';...
                      'Mullen, 1983','Mullen, E.D., 1983. MnO/TiO2/P2O5: a minor element discriminant for basaltic rocks of oceanic environments and its implications for petrogenesis. Earth and Planetary Science Letters 62, 53-62.';...
                      'Pearce et al., 1975','Pearce, T.H., Gorman, B.E., Birkett, T.C., 1975. The TiO2–K2O–P2O5 diagram: A method of discriminating between oceanic and non-oceanic basalts. Earth and Planetary Science Letters 24, 419-426.';...
                      'Pearce et al., 1977','Pearce, T.H., Gorman, B.E., Birkett, T.C., 1977. The relationship between major element chemistry and tectonic environment of basic and intermediate volcanic rocks. Earth and Planetary Science Letters 36, 121-132.';...
                      'Condie, 2005','Condie, K.C., 2005. High field strength element ratios in Archean basalts: a window to evolving sources of mantle plumes? Lithos 79, 491-504.';...
                      'Condie, 2005','Condie, K.C., 2005. High field strength element ratios in Archean basalts: a window to evolving sources of mantle plumes? Lithos 79, 491-504.';...
                      'Fitton et al., 1997','Fitton, J.G., Saunders, A.D., Norry, M.J., Hardarson, B.S., Taylor, R.N., 1997. Thermal and chemical structure of the Iceland plume. Earth and Planetary Science Letters 153, 197-208.';...
                      'Meschede, 1986','Meschede, M., 1986. A method of discriminating between different types of mid-ocean ridge basalts and continental tholeiites with the NbZrY diagram. Chemical Geology 56, 207-218.';...
                      'Pearce & Cann, 1973','Pearce, J.A., Cann, J.R., 1973. Tectonic setting of basic volcanic rocks determined using trace element analyses. Earth and Planetary Science Letters 19, 290-300.';...
                      'Pearce & Cann, 1973','Pearce, J.A., Cann, J.R., 1973. Tectonic setting of basic volcanic rocks determined using trace element analyses. Earth and Planetary Science Letters 19, 290-300.';...
                      'Pearce & Cann, 1973','Pearce, J.A., Cann, J.R., 1973. Tectonic setting of basic volcanic rocks determined using trace element analyses. Earth and Planetary Science Letters 19, 290-300.';...
                      'Wood, 1980','Wood, D.A., 1980. The application of a ThHfTa diagram to problems of tectonomagmatic classification and to establishing the nature of crustal contamination of basaltic lavas of the British Tertiary Volcanic Province. Earth and Planetary Science Letters 50, 11-30.';...
                      'Cabanis & Lecolle, 1989','Cabanis, B., Lecolle, M., 1989. The La/10-Y/15-Nb/8 diagram: a tool for discriminating volcanic series and evidencing continental crust magmatic mixtures and/or contamination [La diagramme La/10-Y/15-Nb/8: un outil pour la discrimination des series volcaniques et la mise en evidence des  processus de melange et/ou de contamination crustale]. Comptes Rendus - Academie des Sciences, Serie II 309, 2023-2029.';...
                      'Hollocher et al., 2012','Hollocher, K., Robinson, P., Walsh, E., and Roberts, D., 2012. Geochemistry of amphibolite-facies volcanics and gabbros of the Støren Nappe in extensions west and southwest of Trondheim, Western Gneiss Region, Norway: a key to correlations and paleotectonic settings.  American Journal of Science, v. 312, p. 357-416.';...
                      'Hollocher et al., 2012','Hollocher, K., Robinson, P., Walsh, E., and Roberts, D., 2012. Geochemistry of amphibolite-facies volcanics and gabbros of the Støren Nappe in extensions west and southwest of Trondheim, Western Gneiss Region, Norway: a key to correlations and paleotectonic settings.  American Journal of Science, v. 312, p. 357-416.';...
                      'Hollocher et al., 2012','Hollocher, K., Robinson, P., Walsh, E., and Roberts, D., 2012. Geochemistry of amphibolite-facies volcanics and gabbros of the Støren Nappe in extensions west and southwest of Trondheim, Western Gneiss Region, Norway: a key to correlations and paleotectonic settings.  American Journal of Science, v. 312, p. 357-416.';...
                      'Hollocher et al., 2012','Hollocher, K., Robinson, P., Walsh, E., and Roberts, D., 2012. Geochemistry of amphibolite-facies volcanics and gabbros of the Støren Nappe in extensions west and southwest of Trondheim, Western Gneiss Region, Norway: a key to correlations and paleotectonic settings.  American Journal of Science, v. 312, p. 357-416.';...
                      'Shervais, 1982','Shervias, J.W., 1982, Ti-V plots and the petrogenesis of modern and ophiolitic lavas.  Earth and Planetary Science Letters, v. 59, p. 101-118.';...
                      'Pearce, 1975','Pearce, J. A. 1975. Basalt geochemistry used to investigate past tectonic environments on Cyprus. Tectonophysics, 25, 41-67.';...
                      'Dilek et al., 2007','Dilek, Y., Furnes, H., and Shallo, M., 2007. Suprasubduction zone ophiolite formation along the periphery of Mesozoic Gondwana. Gondwana Research, 11, 453-475.';...
                      'Dilek & Furnes, 2009','Dilek, Y. and Furnes, H., 2009. Structure and geochemistry of Tethyan ophiolites and their petrogenesis in subduction rollback systems.  Lithos, 113, 1-20.';...
                      'Pearce & Norry, 1979','Pearce, J.A., Norry, M.J., 1979. Petrogenetic implications of Ti, Zr, Y, and Nb. Variations in volcanic rocks. Contributions to Mineralogy and Petrology, 69, 33-37.';...
                      'Pearce, 1981','Pearce, J.A., Alabaster, T., Scheton, A. W. and Searle, M. P., 1981. The Oman ophiolite as a Cretaceous arc-basin complex: Evidence and implications. Philosophical Transactions Royal Society of London, 299-317.';...
                      'Pearce, 1982','Pearce, J.A., 1982. Trace element characteristics of lavas from destructive plate boundaries, 525-548. In: Thorp, R.S. (Eds.). Andesites: Orogenic Andesites and Related Rocks, John Wiley and Sons, New York, 724 pp.';...
                      'Pearce, 1982','Pearce, J.A., 1982. Trace element characteristics of lavas from destructive plate boundaries, 525-548. In: Thorp, R.S. (Eds.). Andesites: Orogenic Andesites and Related Rocks, John Wiley and Sons, New York, 724 pp.';...
                      'Pearce, 1982','Pearce, J.A., 1982. Trace element characteristics of lavas from destructive plate boundaries, 525-548. In: Thorp, R.S. (Eds.). Andesites: Orogenic Andesites and Related Rocks, John Wiley and Sons, New York, 724 pp.';...
                      'Pearce, 1983','Pearce, J.A., 1983. Role of the sub-continental lithosphere in magma genesis at acrive continental margins, 230-249. In: Hawkesworth, C.J., Norry, M.J. (Eds.). Continental Basalts and Mantle Xenoliths, Shiva Publishing Ltd., Cambridge, Mass., 272 pp.';...
                      'Pearce, 1983','Pearce, J.A., 1983. Role of the sub-continental lithosphere in magma genesis at acrive continental margins, 230-249. In: Hawkesworth, C.J., Norry, M.J. (Eds.). Continental Basalts and Mantle Xenoliths, Shiva Publishing Ltd., Cambridge, Mass., 272 pp.';...
                      'Pearce et al., 1984','Pearce, J.A., Harris, N.B.W., Tindle, A.G., 1984. Trace element discrimination diagrams for the tectonic interpretation of granitic rocks. Journal of Petrology 25, 956-983.';...
                      'Pearce et al., 1984','Pearce, J.A., Harris, N.B.W., Tindle, A.G., 1984. Trace element discrimination diagrams for the tectonic interpretation of granitic rocks. Journal of Petrology 25, 956-983.';...
                      'Pearce et al., 1984','Pearce, J.A., Harris, N.B.W., Tindle, A.G., 1984. Trace element discrimination diagrams for the tectonic interpretation of granitic rocks. Journal of Petrology 25, 956-983.';...
                      'Pearce et al., 1984','Pearce, J.A., Harris, N.B.W., Tindle, A.G., 1984. Trace element discrimination diagrams for the tectonic interpretation of granitic rocks. Journal of Petrology 25, 956-983.';...
                      };
end