function [plotax] = lines_mel_cpx_ol_volcanic(control,plotax)

% Line segment #01
line = 2;
plot([0.05000 0.95000],[0.08700 0.08700],...
        'LineWidth',control.setup.lines(1,line).LineWidth.*control.scafac,...
        'LineStyle',control.setup.lines(1,line).LineStyle,...
        'Color',control.setup.lines(1,line).Color);

% Line segment #02
line = 2;
plot([0.85000 0.45000],[0.08700 0.77900],...
        'LineWidth',control.setup.lines(1,line).LineWidth.*control.scafac,...
        'LineStyle',control.setup.lines(1,line).LineStyle,...
        'Color',control.setup.lines(1,line).Color);

end