function [control] = sediplot_control

% Title of the program
control.title = 'SediPlot v1.0';

% Name of the program
control.program = 'SediPlot';

% Number valid header entries
control.header.m = 16;
% Valid header and fulltext header entries
control.header.valid = {...
                        'Gravel','> 2 mm','Gravel','%';...
                        'Sand','2 - 0.063 mm','Sand','%';...
                        'Mud','< 0.063 mm','Mud','%';...
                        'Silt','0.063 - 0.002 mm','Silt','%';...
                        'Clay','< 0.002 mm','Clay','%';...
                        'Qt','Quartz (total)','Qt','%';...
                        'F','Feldspar','F','%';...
                        'L','Lithic fragments','L','%';...
                        'Qp','Quartz (polycrystalline)','Qp','%';...
                        'Qm','Quartz (monocrystalline)','Qm','%';...
                        'Lt','Total aphanitic lithic grains','Lt','%';...
                        'Lm','Metamorphic aphanitic lithic grains','Lm','%';...
                        'Lv','volcanic-hypabyssal aphanitic lithic grains','Lv','%';...
                        'Ls','Sedimentary aphanitic grains','Ls','%';...
                        'Lvm','Volcanic-hypabyssal and metavolcanic aphanitic lithic grains','Lvm','%';...
                        'Lsm','Sedimentary and metasedimentary lithic grains','Lsm','%';...
                        };

% Number of plots
control.plots.m = 10;
% List of plot for button names and plot information
control.plots.list = {...
                      'Mud-Gravel-Sand diagram','ternary',{'Mud';'Gravel';'Sand'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'sedimentary rocks classification','net','all','sedimentary rocks','all','Mud-Gravel-Sand diagram (after Folk (1954))';...
                      'Sand-Silt-Clay diagram','ternary',{'Clay';'Sand';'Silt'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'sedimentary rocks classification','net','all','sedimentary rocks','all','Sand-Silt-Clay diagram (after Folk (1954))';...
                      'Qt-F-L (0-15% matrix) diagram','ternary',{'L';'Qt';'F'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'sedimentary rocks classification','net','all','sedimentary rocks','all','Qt-F-L (0-15% matrix) diagram (after Dott (1964), Pettijohn (1984))';...
                      'Qt-F-L (15-75% matrix) diagram','ternary',{'L';'Qt';'F'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'sedimentary rocks classification','net','all','sedimentary rocks','all','Qt-F-L (15-75% matrix) diagram (after Dott (1964), Pettijohn (1984))';...
                      'Qt-F-L diagram','ternary',{'L';'Qt';'F'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'sedimentary rocks classification','net','all','sedimentary rocks','all','Qt-F-L diagram (after Folk (1965))';...
                      'Qp-Lv-Ls+Lm provenance diagram','ternary',{'Ls + Lm';'Qp';'Lv'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'sediment provenance classification','net','all','sedimentary rocks','all','Qp-Lv-Ls+Lm provenance diagram (after Dickinson & Suczek (1979))';...
                      'Qm-F-Lt provenance diagram','ternary',{'Lt';'Qm';'F'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'sediment provenance classification','net','all','sedimentary rocks','all','Qm-F-Lt provenance diagram (after Dickinson & Suczek (1979))';...
                      'Qt-F-L provenance diagram','ternary',{'L';'Qt';'F'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'sediment provenance classification','net','all','sedimentary rocks','all','Qt-F-L provenance diagram (after Dickinson & Suczek (1979))';...
                      'Lm-Lv-Ls provenance diagram','ternary',{'Ls';'Lm';'Lv'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'sediment provenance classification','net','all','sedimentary rocks','all','Lm-Lv-Ls provenance diagram (after Ingersoll & Suczek (1979))';...
                      'Qp-Lvm-Lsm provenance diagram','ternary',{'Lsm';'Qp';'Lvm'},{'fraction';'fraction';'fraction'},{'-';'-';'-'},'sediment provenance classification','net','all','sedimentary rocks','all','Qp-Lvm-Lsm provenance diagram (after Ingersoll & Suczek (1979))';...
                      };
% List of plot for button names and plot information
control.plots.description = {...
                      'Folk (1954)','Folk, R., 1965. The Petrology of Sedimentary Rocks. Hemphill Publishing Company.','Mud-Gravel-Sand classification diagram (Folk, 1965)';...
                      'Folk (1954)','Folk, R., 1965. The Petrology of Sedimentary Rocks. Hemphill Publishing Company.','Sand-Silt-Clay classification diagram (Folk, 1965)';...
                      'Dott (1964), Pettijohn (1984)','Dott, R.H.J., 1964. Wacke, Graywacke and Matrix--What Approach to Immature Sandstone Classification? SEPM J. Sediment. Res. Vol. 34, 625–632. , Pettijohn, F.J., 1984. Sedimentary Rocks, 3rd ed. CBS Pulishers and Distributors, New Delhi.','Qt-F-L (0-15% matrix) classification diagram (Dott, 1964, Pettijohn, 1984)';...
                      'Dott (1964), Pettijohn (1984)','Dott, R.H.J., 1964. Wacke, Graywacke and Matrix--What Approach to Immature Sandstone Classification? SEPM J. Sediment. Res. Vol. 34, 625–632. , Pettijohn, F.J., 1984. Sedimentary Rocks, 3rd ed. CBS Pulishers and Distributors, New Delhi.','Qt-F-L (15-75% matrix) classification diagram (Dott, 1964, Pettijohn, 1984)';...
                      'Folk (1965)','Folk, RL, 1965. The Petrology of Sedimentary Rocks, Hemphill, 182pp.','Qt-L-F classification diagram (Folk, 1965)';...
                      'Dickinson & Suczek (1979)','Dickinson, W & Suczek, CA, 1979. Plate Tectonics and Sandstone Compositions, AAPG Bulletin, 63(12), 2164-2182.','Qv-Lv-Ls+Lm provenance diagram (Dickinson & Suczek, 1979)';...
                      'Dickinson & Suczek (1979)','Dickinson, W & Suczek, CA, 1979. Plate Tectonics and Sandstone Compositions, AAPG Bulletin, 63(12), 2164-2182.','Qm-Lt-F provenance diagram (Dickinson & Suczek, 1979)';...
                      'Dickinson & Suczek (1979)','Dickinson, W & Suczek, CA, 1979. Plate Tectonics and Sandstone Compositions, AAPG Bulletin, 63(12), 2164-2182.','Qt-L-F provenance diagram (Dickinson & Suczek, 1979)';...
                      'Ingersoll & Suczek (1979)','Ingersoll, RV & Suczek, CA, 1979. Petrology and provenance of Neogene sand from Nicobar and Bengal fans, DSDP sites 211 and 218, Journal of Sedimentary Petrology, 49(4), 1217-1228.','Lm-Lv-Ls provenance diagram (Ingersoll & Suczek, 1979)';...
                      'Ingersoll & Suczek (1979)','Ingersoll, RV & Suczek, CA, 1979. Petrology and provenance of Neogene sand from Nicobar and Bengal fans, DSDP sites 211 and 218, Journal of Sedimentary Petrology, 49(4), 1217-1228.','Qp-Lvm-Lvs provenance diagram (Ingersoll & Suczek, 1979)';...
                      };
end