function [label,tmp_label] = defaults_label(nr,label,tmp_label)
    if label.op.op == false || label.op.override == true
        switch nr
            case 1
            % Label 1
            label = struct('FontName','Arial','FontWeight','bold',...
                                             'FontAngle','normal','FontSize',10,...
                                             'Color',[0,0,0],'FontUnits','points',...
                                             'VertAlign','Middle','HoriAlign','Center',...
                                             'op',struct('op',label.op.op,'disp',label.op.disp,'override',label.op.override));
            case 2
            % Label 2
            label = struct('FontName','Arial','FontWeight','bold',...
                                             'FontAngle','normal','FontSize',8,...
                                             'Color',[0,0,0],'FontUnits','points',...
                                             'VertAlign','Middle','HoriAlign','Center',...
                                             'op',struct('op',label.op.op,'disp',label.op.disp,'override',label.op.override));
            case 3
            % Label 3
            label = struct('FontName','Arial','FontWeight','bold',...
                                             'FontAngle','normal','FontSize',8,...
                                             'Color',[0,0,0],'FontUnits','points',...
                                             'VertAlign','Middle','HoriAlign','Center',...
                                             'op',struct('op',label.op.op,'disp',label.op.disp,'override',label.op.override));
            case 4
            % Label 4
            label = struct('FontName','Arial','FontWeight','bold',...
                                             'FontAngle','normal','FontSize',8,...
                                             'Color',[0,0,0],'FontUnits','points',...
                                             'VertAlign','Middle','HoriAlign','Center',...
                                             'op',struct('op',label.op.op,'disp',label.op.disp,'override',label.op.override));
            case 5
            % Label 5
            label = struct('FontName','Arial','FontWeight','bold',...
                                             'FontAngle','normal','FontSize',8,...
                                             'Color',[0,0,0],'FontUnits','points',...
                                             'VertAlign','Middle','HoriAlign','Center',...
                                             'op',struct('op',label.op.op,'disp',label.op.disp,'override',label.op.override));
            case 6
            % Label 6
            label = struct('FontName','Arial Narrow','FontWeight','normal',...
                                             'FontAngle','normal','FontSize',8,...
                                             'Color',[0,0,0],'FontUnits','points',...
                                             'VertAlign','Middle','HoriAlign','Center',...
                                             'op',struct('op',label.op.op,'disp',label.op.disp,'override',label.op.override));
            case 7
            % Label 7
            label = struct('FontName','Arial Narrow','FontWeight','normal',...
                                             'FontAngle','normal','FontSize',8,...
                                             'Color',[0,0,0],'FontUnits','points',...
                                             'VertAlign','Middle','HoriAlign','Center',...
                                             'op',struct('op',label.op.op,'disp',label.op.disp,'override',label.op.override));
            case 8
            % Label 8
            label = struct('FontName','Arial Narrow','FontWeight','normal',...
                                             'FontAngle','normal','FontSize',8,...
                                             'Color',[0,0,0],'FontUnits','points',...
                                             'VertAlign','Middle','HoriAlign','Center',...
                                             'op',struct('op',label.op.op,'disp',label.op.disp,'override',label.op.override));
            case 9
            % Label 9
            label = struct('FontName','Arial Narrow','FontWeight','normal',...
                                             'FontAngle','normal','FontSize',8,...
                                             'Color',[0,0,0],'FontUnits','points',...
                                             'VertAlign','Middle','HoriAlign','Center',...
                                             'op',struct('op',label.op.op,'disp',label.op.disp,'override',label.op.override));
        end
        tmp_label = label;
    end
end

