function [symbol,tmp_symbol] = defaults_marker(nr,symbol,tmp_symbol)
    if symbol.op.op == false || symbol.op.override == true
        switch nr
            case 1
            % Dataset 1
            symbol  = struct('size',12,'symbol',1,'edgew',1,...
                             'mec',[0 0 0],'mfc',[1 0 0],...
                             'op',struct('op',symbol.op.op,'override',symbol.op.op));
            case 2
            % Dataset 2
            symbol   = struct('size',11,'symbol',2,'edgew',1,...
                              'mec',[0 0 0],'mfc',[0 1 0],...
                              'op',struct('op',symbol.op.op,'override',symbol.op.op));
            case 3
            % Dataset 3
            symbol   = struct('size',10,'symbol',3,'edgew',1,...
                              'mec',[0 0 0],'mfc',[0 0 1],...
                              'op',struct('op',symbol.op.op,'override',symbol.op.op));
            case 4
            % Dataset 4
            symbol   = struct('size',9,'symbol',4,'edgew',1,...
                              'mec',[0 0 0],'mfc',[1 1 0],...
                              'op',struct('op',symbol.op.op,'override',symbol.op.op)); 
            case 5
            % Dataset 5
            symbol   = struct('size',8,'symbol',5,'edgew',1,...
                              'mec',[0 0 0],'mfc',[0 1 1],...
                              'op',struct('op',symbol.op.op,'override',symbol.op.op)); 
            case 6
            % Dataset 6
            symbol   = struct('size',9,'symbol',6,'edgew',1,...
                              'mec',[0 0 0],'mfc',[1 0 1],...
                              'op',struct('op',symbol.op.op,'override',symbol.op.op));  
            case 7
            % Dataset 7
            symbol   = struct('size',10,'symbol',7,'edgew',1,...
                              'mec',[0 0 0],'mfc',[1 0.5 0.5],...
                              'op',struct('op',symbol.op.op,'override',symbol.op.op));
            case 8
            % Dataset 8
            symbol   = struct('size',11,'symbol',8,'edgew',1,...
                              'mec',[0 0 0],'mfc',[0.5 0.5 1],...
                              'op',struct('op',symbol.op.op,'override',symbol.op.op));
            case 9
            % Dataset 9
            symbol   = struct('size',12,'symbol',9,'edgew',1,...
                              'mec',[0 0 0],'mfc',[0.5 1 0.5],...
                              'op',struct('op',symbol.op.op,'override',symbol.op.op));
        end
        tmp_symbol = symbol;
    end
end