function tool_chelements
%% 00a Create the figure
fig_elements = figure('Visible','off');
% Set units of the figure to pixel and hide menu bar.
set(fig_elements,'Units','pixel','MenuBar','none');
% Set size and position (absolute pixel) of the figure and set name of the GUI
set(fig_elements,'Position',[50,50,400,360],'Name','Chelements - Chemical Elements');
% Change the background color of the GUI to black
set(fig_elements,'Color',[1.,1.,1.]);
%% 00b Load the database
% Load the chemical database
[elements chem] = elements_database;
% Get the number of available elements
[m ~] = size(elements); elements_string = cell(m,1);
% Create strings for each element
for i = 1:m
    elements_string{i,1} = [num2str(chem.(elements{i,1}).atomicnumber) ' - ' chem.(elements{i,1}).symbol];
end
%% 01 Create popup to select elements
elements_popup = uicontrol('Style','popup',...
                           'Parent',fig_elements,'Units','normalized',...
                           'Value',chem.H.atomicnumber,'Position',[0.02 0.88 0.96 0.1],...
                           'ForegroundColor',[1. 1. 1.],'BackgroundColor',[.0 .0 .0],...
                           'FontSize',14,'FontWeight','Bold',...
                           'String',elements_string,...
                           'HorizontalAlignment','Left',...
                           'ToolTipString','Click to select another chemical element!',...
                           'Callback',@elements_callback);
%% 02 Create something to display the chemical elements
elements_symbol = uicontrol('Style','text','Units','normalized',......
                                                 'Parent',fig_elements,...
                                                 'Position',[0.25 0.15 0.7 0.6],...
                                                 'ForegroundColor',[.0 .0 1.0],'BackgroundColor',[1. 1. 1.],...
                                                 'String',chem.H.symbol,...
                                                 'HorizontalAlignment','Left',...
                                                 'FontSize',120,'FontWeight','Bold');
elements_name = uicontrol('Style','text','Units','normalized',......
                                                 'Parent',fig_elements,...
                                                 'Position',[0.27 0.11 0.4 0.1],...
                                                 'ForegroundColor',[.0 .0 .0],'BackgroundColor',[1. 1. 1.],...
                                                 'String',chem.H.name,...
                                                 'HorizontalAlignment','Left',...
                                                 'FontSize',18,'FontWeight','Bold');
elements_number = uicontrol('Style','text','Units','normalized',......
                                                 'Parent',fig_elements,...
                                                 'Position',[0.0325 0.46 0.21 0.18],...
                                                 'ForegroundColor',[.0 .0 .0],'BackgroundColor',[1. 1. 1.],...
                                                 'String',num2str(chem.H.atomicnumber),...
                                                 'HorizontalAlignment','Right',...
                                                 'FontSize',36,'FontWeight','Bold');
elements_molarweight = uicontrol('Style','text','Units','normalized',......
                                                 'Parent',fig_elements,...
                                                 'Position',[0.27 0.64 0.25 0.1],...
                                                 'ForegroundColor',[.0 .0 .0],'BackgroundColor',[1. 1. 1.],...
                                                 'String',num2str(chem.H.molarweight),...
                                                 'HorizontalAlignment','Left',...
                                                 'FontSize',18,'FontWeight','Bold');
elements_electro = uicontrol('Style','text','Units','normalized',......
                                                 'Parent',fig_elements,...
                                                 'Position',[0.52 0.64 0.1 0.1],...
                                                 'ForegroundColor',[.0 .8 .0],'BackgroundColor',[1. 1. 1.],...
                                                 'String',num2str(chem.H.electronegativity),...
                                                 'HorizontalAlignment','Left',...
                                                 'FontSize',18,'FontWeight','Bold');
%% 03 Callback for element selection
function elements_callback(~,~)
    % Get the current selection
    selection = get(elements_popup,'Value');
    % Check the state of the element and change symbol and color
    if strcmpi(chem.(elements{selection,1}).state,'gaseous')
        set(elements_symbol,'String',chem.(elements{selection,1}).symbol,'ForeGroundColor',[0.0,0.0,1.0])
    elseif strcmpi(chem.(elements{selection,1}).state,'solid')
        set(elements_symbol,'String',chem.(elements{selection,1}).symbol,'ForeGroundColor',[0.0,0.0,0.0])
    elseif strcmpi(chem.(elements{selection,1}).state,'liquid')
        set(elements_symbol,'String',chem.(elements{selection,1}).symbol,'ForeGroundColor',[0.0,0.0,1.0])
    elseif strcmpi(chem.(elements{selection,1}).state,'radioactive')
        set(elements_symbol,'String',chem.(elements{selection,1}).symbol,'ForeGroundColor',[1.0,0.0,0.0])
    else
        set(elements_symbol,'String',chem.(elements{selection,1}).symbol,'ForeGroundColor',[0.3,0.3,0.3])
    end
    % Change the element name
    set(elements_name,'String',chem.(elements{selection,1}).name)
    % Change the atomic number
    set(elements_number,'String',chem.(elements{selection,1}).atomicnumber)
    % Change the electronegativity
    set(elements_electro,'String',sprintf('%.1f',(chem.(elements{selection,1}).electronegativity)))
    
    % Change the molar weight
    if ischar(chem.(elements{selection,1}).molarweight)
    set(elements_molarweight,'String',num2str(chem.(elements{selection,1}).molarweight))
    set(elements_molarweight,'ForeGroundColor',[0.3 0.3 0.3])
    else
    set(elements_molarweight,'String',chem.(elements{selection,1}).molarweight)
    set(elements_molarweight,'ForeGroundColor',[0.0 0.0 0.0])
    end
end
%% 00c Make the GUI visible
set(fig_elements,'Visible','on');
end